import { Prisma } from '@prisma/client';
import { prisma } from '../../lib/prisma.js';
import { costStatusOf } from '../../lib/cost-status.js';
import { businessDateKey, expiryStatus } from '../../lib/inventory-lot.js';

const D=(value:Prisma.Decimal|number|string)=>new Prisma.Decimal(value);const n=(value:unknown)=>Number(value??0);
const daysAt=(expiry:Date|null,businessDate:string)=>expiry?Math.round((Date.parse(expiry.toISOString().slice(0,10))-Date.parse(businessDate))/86_400_000):null;
const sourceOf=(status:string,source?:string|null)=>status==='MISSING'?'UNKNOWN':status==='ZERO'?'EXPLICIT_ZERO':source==='PURCHASE'?'PURCHASE':source==='PRODUCTION'?'PRODUCTION':'UNKNOWN';

export async function currentSnapshotPreview(companyId:string,client:Prisma.TransactionClient|typeof prisma=prisma){
 const businessDate=businessDateKey();const balances=await client.stockBalance.findMany({where:{warehouse:{companyId},item:{companyId,deletedAt:null}},include:{warehouse:true,lot:true,item:{include:{baseUnit:true,category:true,priceHistory:{orderBy:{createdAt:'desc'},take:1}}}}});
 const lines=balances.map(balance=>{const cost=n(balance.item.lastCost);const status=costStatusOf({lastCost:cost,priceRecordCount:balance.item.priceHistory.length});const recognized=status==='MISSING'?null:cost;return{itemId:balance.itemId,itemCode:balance.item.code,itemName:balance.item.name,warehouseId:balance.warehouseId,warehouseCode:balance.warehouse.code,warehouseName:balance.warehouse.name,lotId:balance.lotId,lotNo:balance.lot?.lotNo??null,locationId:balance.locationId,onHand:D(balance.onHand),reserved:D(balance.reserved),baseUnitId:balance.item.baseUnitId,baseUnitCode:balance.item.baseUnit.code,recognizedUnitCost:recognized==null?null:D(recognized),costStatus:status,estimatedValue:recognized==null?null:D(balance.onHand).mul(recognized),costSource:sourceOf(status,balance.item.priceHistory[0]?.source),itemType:balance.item.type,categoryId:balance.item.categoryId,categoryName:balance.item.category?.name??null,expiryDate:balance.lot?.expiryDate??null,expiryStatus:balance.lot?expiryStatus(balance.lot.expiryDate,new Date(`${businessDate}T00:00:00.000Z`)):null,daysRemaining:daysAt(balance.lot?.expiryDate??null,businessDate)};});
 const known=lines.filter(line=>line.costStatus!=='MISSING');const unknown=lines.length-known.length;return{businessDate,lines,knownInventoryValue:known.reduce((sum,line)=>sum.plus(line.estimatedValue??0),D(0)),knownBalanceCount:known.length,unknownCostBalanceCount:unknown,negativeStockCount:lines.filter(line=>line.onHand.lt(0)).length,valuationCompleteness:lines.length?D(known.length).mul(100).div(lines.length):D(100)};
}

export async function createInventorySnapshot(companyId:string,userId:string,source='MANUAL'){
 try{return await prisma.$transaction(async tx=>{const preview=await currentSnapshotPreview(companyId,tx);const existing=await tx.inventoryValuationSnapshot.findUnique({where:{companyId_businessDate:{companyId,businessDate:new Date(`${preview.businessDate}T00:00:00.000Z`)}}});if(existing)return{snapshot:existing,created:false,lineCount:await tx.inventoryValuationSnapshotLine.count({where:{snapshotId:existing.id}})};
 const snapshot=await tx.inventoryValuationSnapshot.create({data:{companyId,businessDate:new Date(`${preview.businessDate}T00:00:00.000Z`),source,knownInventoryValue:preview.knownInventoryValue,knownBalanceCount:preview.knownBalanceCount,unknownCostBalanceCount:preview.unknownCostBalanceCount,negativeStockCount:preview.negativeStockCount,valuationCompleteness:preview.valuationCompleteness,createdById:userId,lines:{create:preview.lines}}});
 await tx.auditLog.create({data:{userId,companyId,action:'INVENTORY_SNAPSHOT_CREATED',entity:'InventoryValuationSnapshot',entityId:snapshot.id,after:{businessDate:preview.businessDate,lineCount:preview.lines.length,knownBalanceCount:preview.knownBalanceCount,unknownCostBalanceCount:preview.unknownCostBalanceCount}}});return{snapshot,created:true,lineCount:preview.lines.length};},{isolationLevel:Prisma.TransactionIsolationLevel.RepeatableRead,maxWait:10_000,timeout:30_000});
 }catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2002'){const date=new Date(`${businessDateKey()}T00:00:00.000Z`);const snapshot=await prisma.inventoryValuationSnapshot.findUniqueOrThrow({where:{companyId_businessDate:{companyId,businessDate:date}}});return{snapshot,created:false,lineCount:await prisma.inventoryValuationSnapshotLine.count({where:{snapshotId:snapshot.id}})}}throw error}
}
