import { Prisma } from '@prisma/client';
import { prisma } from '../../lib/prisma.js';
import { num } from '../../lib/http.js';
import { costStatusOf } from '../../lib/cost-status.js';
import { toBaseQuantity, type ConvEdge } from '../../lib/unit-convert.js';
import { computeSavedVersionCost } from '../recipes/recipe.route.js';

const D=(v:Prisma.Decimal.Value=0)=>new Prisma.Decimal(v);const TYPES=['RETAIL','WHOLESALE','AGENT','SPECIAL'] as const;
export type SimulationInput={recipeVersionId:string;ingredientOverrides?:{itemId:string;unitCost?:number;unitCostPercent?:number;quantity?:number;quantityPercent?:number}[];yieldQty?:number;sellingPrices?:Partial<Record<typeof TYPES[number],number>>;targetMarginPercent?:number;targetMarkupPercent?:number};
const priceMetrics=(cost:Prisma.Decimal,price:Prisma.Decimal)=>{const profit=price.minus(cost);return{sellingPrice:num(price),grossProfit:num(profit),marginPercent:price.gt(0)?num(profit.div(price).mul(100)):null,markupPercent:cost.gt(0)?num(profit.div(cost).mul(100)):null,isLoss:price.lt(cost)}};

export async function simulateProfit(companyId:string,input:SimulationInput){
 const version=await prisma.recipeVersion.findFirst({
  where:{id:input.recipeVersionId,recipe:{companyId,deletedAt:null}},
  include:{recipe:{include:{product:{include:{sellingPrices:{where:{isActive:true}}}}}},yieldUnit:true,ingredients:{orderBy:{sortOrder:'asc'},include:{unit:true,item:{include:{baseUnit:true,purchaseUnit:true,_count:{select:{priceHistory:true}},priceHistory:{orderBy:{createdAt:'desc'},take:1}}},childRecipe:true}}},
 });if(!version)return null;
 const saved=await computeSavedVersionCost(companyId,version.id);if(!saved) return null;const edges:ConvEdge[]=(await prisma.unitConversion.findMany({select:{fromUnitId:true,toUnitId:true,factor:true}})).map(x=>({fromUnitId:x.fromUnitId,toUnitId:x.toUnitId,factor:num(x.factor)}));const overrides=new Map((input.ingredientOverrides??[]).map(x=>[x.itemId,x]));
 let simIngredient=D(0),simPackaging=D(0);const lines=[] as Record<string,unknown>[];let known=0,eligible=0;
 for(const row of version.ingredients){if(!row.item){continue}eligible++;const item=row.item,status=costStatusOf({lastCost:num(item.lastCost),priceRecordCount:item._count.priceHistory}),baselineCost=status==='MISSING'?null:item.lastCost,baseQty=toBaseQuantity(num(row.quantity),row.unitId,{baseUnitId:item.baseUnitId,purchaseUnitId:item.purchaseUnitId,purchaseToBaseFactor:num(item.purchaseToBaseFactor)},edges),override=overrides.get(item.id);let simulatedRecipeQty=D(override?.quantity??row.quantity);if(override?.quantityPercent!==undefined)simulatedRecipeQty=row.quantity.mul(D(1).plus(D(override.quantityPercent).div(100)));const simulatedQtyBase=toBaseQuantity(num(simulatedRecipeQty),row.unitId,{baseUnitId:item.baseUnitId,purchaseUnitId:item.purchaseUnitId,purchaseToBaseFactor:num(item.purchaseToBaseFactor)},edges);let simulatedCost=override?.unitCost!==undefined?D(override.unitCost):baselineCost;if(override?.unitCostPercent!==undefined&&baselineCost!=null)simulatedCost=baselineCost.mul(D(1).plus(D(override.unitCostPercent).div(100)));const waste=D(1).plus(row.wastePercent.div(100)),baselineLine=baselineCost!=null&&baseQty!=null?D(baseQty).mul(waste).mul(baselineCost):null,simulatedLine=simulatedCost!=null&&simulatedQtyBase!=null?D(simulatedQtyBase).mul(waste).mul(simulatedCost):null;if(baselineCost!=null)known++;if(simulatedLine!=null){if(row.componentType==='PACKAGING')simPackaging=simPackaging.plus(simulatedLine);else simIngredient=simIngredient.plus(simulatedLine)}lines.push({itemId:item.id,itemCode:item.code,itemName:item.name,itemType:item.type,unitCode:row.unit?.code??item.baseUnit.code,baselineQuantity:num(row.quantity),simulatedQuantity:num(simulatedRecipeQty),baselineQuantityBase:baseQty,simulatedQuantityBase:simulatedQtyBase,baselineUnitCost:baselineCost==null?null:num(baselineCost),simulatedUnitCost:simulatedCost==null?null:num(simulatedCost),baselineLineCost:baselineLine==null?null:num(baselineLine),simulatedLineCost:simulatedLine==null?null:num(simulatedLine),impact:baselineLine!=null&&simulatedLine!=null?num(simulatedLine.minus(baselineLine)):null,costStatus:status,costSource:status==='MISSING'?'UNKNOWN':status==='ZERO'?'EXPLICIT_ZERO':item.priceHistory[0]?.source??'UNKNOWN',manualCost:baselineCost==null&&override?.unitCost!==undefined});}
 const subRecipe=D(saved.cost.subRecipeCost),simDirect=simIngredient.plus(simPackaging).plus(subRecipe);let simulatedOverhead=D(saved.cost.overheadCost);if(version.overheadMode==='PERCENTAGE'){const base=version.overheadBase==='INGREDIENT'?simIngredient:simDirect;simulatedOverhead=base.mul(version.overheadPercent??0).div(100)}const baselineTotal=D(saved.cost.totalCost),simulatedTotal=simDirect.plus(simulatedOverhead),baselineYield=D(saved.cost.effectiveYield);let simulatedYield=baselineYield;if(input.yieldQty!==undefined){if(version.yieldMode==='BATCH')throw new Error('BATCH_YIELD_NOT_EDITABLE');simulatedYield=D(input.yieldQty).mul(version.yieldPercent).div(100)}if(simulatedYield.lte(0))throw new Error('INVALID_SIMULATED_YIELD');const baselineUnit=baselineTotal.div(baselineYield),simulatedUnit=simulatedTotal.div(simulatedYield);
 const actualPrices=new Map(version.recipe.product.sellingPrices.map(x=>[x.priceType,x.price]));const tiers=TYPES.map(type=>{const bp=actualPrices.get(type)??null,sp=input.sellingPrices?.[type]!==undefined?D(input.sellingPrices[type]!):bp;return{priceType:type,baseline:bp?priceMetrics(baselineUnit,bp):null,simulated:sp?priceMetrics(simulatedUnit,sp):null,overridden:input.sellingPrices?.[type]!==undefined}});
 const targetMargin=input.targetMarginPercent===undefined?null:{percent:input.targetMarginPercent,rawSellingPrice:Number(simulatedUnit.div(D(1).minus(D(input.targetMarginPercent).div(100))).toDecimalPlaces(8).toString())};const targetMarkup=input.targetMarkupPercent===undefined?null:{percent:input.targetMarkupPercent,rawSellingPrice:Number(simulatedUnit.mul(D(1).plus(D(input.targetMarkupPercent).div(100))).toDecimalPlaces(8).toString())};
 const lineImpact=lines.reduce((s,x)=>s.plus((x.impact as number|null)??0),D(0)),yieldImpact=simulatedUnit.minus(simulatedTotal.div(baselineYield)),overheadImpact=simulatedOverhead.minus(saved.cost.overheadCost);const residual=simulatedUnit.minus(baselineUnit).minus(lineImpact.add(overheadImpact).div(baselineYield)).minus(yieldImpact);
 return{label:'SIMULATION / WHAT-IF — ไม่ใช่ข้อมูลจริง',recipe:{id:version.recipe.id,code:version.recipe.code,name:version.recipe.name,product:version.recipe.product},version:{id:version.id,versionNo:version.versionNo,yieldMode:version.yieldMode??(version.yieldUnitId?'ACTUAL':'BATCH'),yieldUnit:version.yieldUnit},coverage:{known,eligible,percent:eligible?known/eligible*100:100,complete:known===eligible},baseline:{totalCost:num(baselineTotal),unitCost:num(baselineUnit),effectiveYield:num(baselineYield),overheadCost:num(saved.cost.overheadCost)},simulated:{totalCost:num(simulatedTotal),unitCost:num(simulatedUnit),effectiveYield:num(simulatedYield),overheadCost:num(simulatedOverhead),costChange:num(simulatedUnit.minus(baselineUnit))},lines,tiers,targets:{margin:targetMargin,markup:targetMarkup,breakEvenSellingPrice:num(simulatedUnit)},bridge:{ingredientImpactPerUnit:num(lineImpact.add(overheadImpact).div(baselineYield)),yieldImpactPerUnit:num(yieldImpact),interactionResidual:num(residual)},warnings:[known<eligible?'COST_DATA_INCOMPLETE':null,tiers.some(x=>x.simulated?.isLoss)?'SIMULATED_PRICE_BELOW_SIMULATED_COST':null].filter(Boolean)};
}
