import { RoleName } from '@prisma/client';

/**
 * PHASE 19 — แคตตาล็อกสิทธิ์และสิทธิ์ตั้งต้นของบทบาท
 *
 * แยกออกมาจาก seed เพื่อให้ seed · สคริปต์ซิงก์ · และคำสั่งตรวจสอบ อ่านจากแหล่งเดียวกัน
 *
 * โมเดลการกำกับดูแลที่ระบบนี้ใช้:
 *   1) "รายการสิทธิ์" (permissions) เป็นของโค้ด — เพิ่มรหัสใหม่ผ่านสคริปต์ได้อย่างปลอดภัย
 *   2) "การผูกสิทธิ์กับบทบาท" (role_permissions) ของฐานผลิต เป็นของฐานข้อมูล
 *      ผู้ดูแลแก้ผ่านหน้าเว็บ (PUT /api/admin/roles/:roleName/permissions) และถือเป็นความจริง
 *   3) ค่าตั้งต้นด้านล่างนี้ใช้ได้เฉพาะตอน bootstrap ฐานเปล่าและฐานทดสอบเท่านั้น
 *      ห้ามนำไปเขียนทับฐานผลิตที่ตั้งค่าไว้แล้ว
 */

export const PERMISSION_CODES: string[] = [
  'COMPANY_VIEW', 'COMPANY_SWITCH', 'DASHBOARD_VIEW', 'PROFILE_VIEW',
  'INGREDIENT_VIEW', 'INGREDIENT_CREATE', 'INGREDIENT_EDIT', 'PACKAGING_VIEW', 'PACKAGING_CREATE', 'PACKAGING_EDIT',
  'RECIPE_VIEW', 'RECIPE_CREATE', 'RECIPE_EDIT', 'RECIPE_APPROVE_IF_NEEDED', 'COSTING_VIEW', 'COSTING_CALCULATE',
  'PRICING_VIEW', 'PRICING_EDIT', 'CUSTOMER_VIEW', 'CUSTOMER_CREATE', 'CUSTOMER_EDIT',
  'ORDER_VIEW', 'ORDER_CREATE', 'ORDER_EDIT', 'ORDER_SEND', 'ORDER_CONFIRM', 'ORDER_CANCEL', 'ORDER_COMPLETE',
  'RECEIVING_VIEW', 'RECEIVING_CREATE', 'RECEIVING_EDIT', 'RECEIVING_CONFIRM', 'STOCK_VIEW', 'STOCK_ISSUE_VIEW', 'STOCK_ISSUE_CREATE', 'STOCK_ISSUE_CONFIRM',
  'INVENTORY_VIEW', 'INVENTORY_ADJUST',
  // PHASE 18 — โอนย้ายระหว่างคลัง
  'STOCK_TRANSFER_VIEW', 'STOCK_TRANSFER_CREATE', 'STOCK_TRANSFER_CONFIRM', 'STOCK_TRANSFER_REVERSE',
  'KPI_VIEW', 'REPORT_VIEW', 'NOTIFICATION_VIEW', 'DOCUMENT_DOWNLOAD', 'DOCUMENT_EMAIL',
  'USER_VIEW', 'USER_MANAGE', 'AUDIT_VIEW', 'ROLE_MANAGE', 'PERMISSION_MANAGE', 'SYSTEM_SETTINGS', 'SECURITY_SETTINGS',
];

export const PERMISSION_DEFINITIONS = PERMISSION_CODES.map((code) => ({ code, description: code }));

/** สิทธิ์ที่ไม่มอบให้ ADMIN — งานดูแลผู้ใช้สงวนไว้ให้ SUPER_ADMIN */
const ADMIN_EXCLUDED = ['USER_MANAGE'];

/** สิทธิ์ที่ไม่มอบให้ MANAGER — งานความปลอดภัยและการแก้สิทธิ์ */
const MANAGER_EXCLUDED = ['ROLE_MANAGE', 'PERMISSION_MANAGE', 'SECURITY_SETTINGS'];

/**
 * สิทธิ์ตั้งต้นของบทบาทที่ระบุรายการไว้ตรง ๆ
 * บทบาทที่ไม่อยู่ในนี้ (WAREHOUSE · EXECUTIVE · VIEWER) ตั้งใจให้เริ่มจากศูนย์
 * แล้วให้ผู้ดูแลกำหนดเองผ่านหน้าเว็บตามหน้างานจริง
 */
const SCOPED_GRANTS: Record<string, string[]> = {
    OPERATIONS: ['COMPANY_VIEW', 'COMPANY_SWITCH', 'DASHBOARD_VIEW', 'PROFILE_VIEW', 'INGREDIENT_VIEW', 'PACKAGING_VIEW', 'RECIPE_VIEW', 'RECIPE_CREATE', 'RECIPE_EDIT', 'COSTING_VIEW', 'ORDER_VIEW', 'ORDER_CONFIRM', 'RECEIVING_VIEW', 'RECEIVING_CREATE', 'RECEIVING_EDIT', 'RECEIVING_CONFIRM', 'STOCK_VIEW', 'STOCK_ISSUE_VIEW', 'STOCK_ISSUE_CREATE', 'STOCK_ISSUE_CONFIRM', 'INVENTORY_VIEW', 'INVENTORY_ADJUST', 'STOCK_TRANSFER_VIEW', 'STOCK_TRANSFER_CREATE', 'STOCK_TRANSFER_CONFIRM', 'STOCK_TRANSFER_REVERSE', 'NOTIFICATION_VIEW', 'DOCUMENT_DOWNLOAD'],
  ORDER_COORDINATOR: ['COMPANY_VIEW', 'COMPANY_SWITCH', 'DASHBOARD_VIEW', 'PROFILE_VIEW', 'CUSTOMER_VIEW', 'CUSTOMER_CREATE', 'CUSTOMER_EDIT', 'ORDER_VIEW', 'ORDER_CREATE', 'ORDER_EDIT', 'ORDER_SEND', 'ORDER_CONFIRM', 'ORDER_CANCEL', 'NOTIFICATION_VIEW', 'DOCUMENT_DOWNLOAD', 'DOCUMENT_EMAIL'],
  CHEF: ['COMPANY_VIEW', 'COMPANY_SWITCH', 'DASHBOARD_VIEW', 'PROFILE_VIEW', 'INGREDIENT_VIEW', 'PACKAGING_VIEW', 'RECIPE_VIEW', 'RECIPE_CREATE', 'RECIPE_EDIT', 'ORDER_VIEW', 'NOTIFICATION_VIEW', 'DOCUMENT_DOWNLOAD'],
  COSTING_STAFF: ['COMPANY_VIEW', 'COMPANY_SWITCH', 'DASHBOARD_VIEW', 'PROFILE_VIEW', 'INGREDIENT_VIEW', 'INGREDIENT_CREATE', 'INGREDIENT_EDIT', 'PACKAGING_VIEW', 'PACKAGING_CREATE', 'PACKAGING_EDIT', 'RECIPE_VIEW', 'RECIPE_CREATE', 'RECIPE_EDIT', 'COSTING_VIEW', 'COSTING_CALCULATE', 'PRICING_VIEW', 'PRICING_EDIT', 'KPI_VIEW', 'REPORT_VIEW', 'NOTIFICATION_VIEW', 'DOCUMENT_DOWNLOAD'],
  // เดิมสิทธิ์เหล่านี้อาศัย role-guard; ย้ายมาเป็น permission-based จึงต้องให้ permission ตรงตามเจตนาเดิม
  PRODUCTION: ['COMPANY_VIEW', 'COMPANY_SWITCH', 'DASHBOARD_VIEW', 'PROFILE_VIEW', 'INGREDIENT_VIEW', 'INGREDIENT_CREATE', 'INGREDIENT_EDIT', 'PACKAGING_VIEW', 'PACKAGING_CREATE', 'PACKAGING_EDIT', 'RECIPE_VIEW', 'RECIPE_CREATE', 'RECIPE_EDIT', 'COSTING_VIEW', 'COSTING_CALCULATE', 'STOCK_VIEW', 'INVENTORY_VIEW', 'RECEIVING_VIEW', 'NOTIFICATION_VIEW', 'DOCUMENT_DOWNLOAD', 'STOCK_TRANSFER_VIEW'],
  PURCHASING: ['COMPANY_VIEW', 'COMPANY_SWITCH', 'DASHBOARD_VIEW', 'PROFILE_VIEW', 'INGREDIENT_VIEW', 'INGREDIENT_CREATE', 'INGREDIENT_EDIT', 'PACKAGING_VIEW', 'PACKAGING_CREATE', 'PACKAGING_EDIT', 'RECEIVING_VIEW', 'RECEIVING_CREATE', 'RECEIVING_EDIT', 'RECEIVING_CONFIRM', 'STOCK_VIEW', 'INVENTORY_VIEW', 'NOTIFICATION_VIEW', 'DOCUMENT_DOWNLOAD', 'STOCK_TRANSFER_VIEW'],
  SALES: ['COMPANY_VIEW', 'COMPANY_SWITCH', 'DASHBOARD_VIEW', 'PROFILE_VIEW', 'RECIPE_VIEW', 'COSTING_VIEW', 'PRICING_VIEW', 'PRICING_EDIT', 'CUSTOMER_VIEW', 'CUSTOMER_CREATE', 'CUSTOMER_EDIT', 'ORDER_VIEW', 'ORDER_CREATE', 'ORDER_EDIT', 'ORDER_SEND', 'NOTIFICATION_VIEW', 'DOCUMENT_DOWNLOAD'],
};

/** สิทธิ์ตั้งต้นของทุกบทบาท รวมกติกาของ SUPER_ADMIN / ADMIN / MANAGER ที่คำนวณจากรายการทั้งหมด */
export const BOOTSTRAP_ROLE_GRANTS: Record<string, string[]> = {
  [RoleName.SUPER_ADMIN]: [...PERMISSION_CODES],
  [RoleName.ADMIN]: PERMISSION_CODES.filter((code) => !ADMIN_EXCLUDED.includes(code)),
  [RoleName.MANAGER]: PERMISSION_CODES.filter((code) => !MANAGER_EXCLUDED.includes(code)),
  ...SCOPED_GRANTS,
};

/** สิทธิ์ตั้งต้นของบทบาทหนึ่ง — ไม่รู้จักหรือไม่ได้กำหนดไว้ คืนรายการว่าง ไม่เดา */
export function bootstrapGrantsFor(roleName: string): string[] {
  return BOOTSTRAP_ROLE_GRANTS[roleName] ?? [];
}
