import { Prisma } from '@prisma/client';
import type { FastifyInstance, FastifyReply } from 'fastify';
import { z } from 'zod';
import { prisma } from '../../lib/prisma.js';
import { num } from '../../lib/http.js';
import { fail, ok } from '../../lib/response.js';
import { requirePermission } from '../auth/auth.guard.js';
import { nextDocumentNo } from '../../lib/inventory-ledger.js';
import { withDocumentNumberRetry } from '../../lib/tx-retry.js';
import { renderBusinessPdf, type BusinessDocument } from '../business/document.service.js';
import { calculatePurchasePlan } from './purchase-planning.service.js';
import { ProductionCalculationError } from '../production/production.service.js';

const D = (value: number | string | Prisma.Decimal) => new Prisma.Decimal(value);
const VIEW = requirePermission('PURCHASE_PLAN_VIEW', 'PURCHASE_PLAN_CREATE', 'PURCHASE_PLAN_EDIT');
const CREATE = requirePermission('PURCHASE_PLAN_CREATE'); const EDIT = requirePermission('PURCHASE_PLAN_EDIT', 'PURCHASE_PLAN_CREATE');
const targetInput = z.object({ recipeId: z.string().min(1), recipeVersionId: z.string().min(1).optional().nullable(), plannedQty: z.number().positive() });
const planInput = z.object({ planDate: z.coerce.date(), warehouseId: z.string().min(1), note: z.string().max(1000).optional().nullable(), targets: z.array(targetInput).min(1).max(100) });
const editInput = planInput.extend({ version: z.number().int().positive() });
const listInput = z.object({ status: z.enum(['DRAFT','READY','CANCELLED']).optional(), dateFrom: z.string().date().optional(), dateTo: z.string().date().optional(), shortageOnly: z.coerce.boolean().optional(), supplierId: z.string().optional(), categoryId: z.string().optional() });

const include = { warehouse: { select: { id: true, code: true, name: true } }, targets: { orderBy: { id: 'asc' as const } }, requirements: { include: { purchaseOrderItems: { where: { purchaseOrder: { status: { not: 'CANCELLED' } } }, select: { orderedQty: true } } }, orderBy: [{ shortageQty: 'desc' as const }, { itemName: 'asc' as const }] } } satisfies Prisma.PurchasePlanInclude;
type Detail = Prisma.PurchasePlanGetPayload<{ include: typeof include }>;

function summary(detail: Detail) { return { materialCount: detail.requirements.length, shortageCount: detail.requirements.filter((line) => num(line.shortageQty) > 0).length, estimatedCost: detail.requirements.reduce((sum, line) => sum + num(line.estimatedCost), 0), targetCount: detail.targets.length }; }
async function serialize(detail: Detail, current = false) {
  let currentOf = new Map<string, { onHand: number; reserved: number; available: number }>();
  if (current) { const rows = await prisma.stockBalance.findMany({ where: { warehouseId: detail.warehouseId, itemId: { in: detail.requirements.map((line) => line.itemId) } }, select: { itemId: true, onHand: true, reserved: true } }); for (const row of rows) { const value = currentOf.get(row.itemId) ?? { onHand: 0, reserved: 0, available: 0 }; value.onHand += num(row.onHand); value.reserved += num(row.reserved); value.available = value.onHand - value.reserved; currentOf.set(row.itemId, value); } }
  return { ...detail, targets: detail.targets.map((line) => ({ ...line, plannedQty: num(line.plannedQty) })), requirements: detail.requirements.map((line) => { const orderedQty = line.purchaseOrderItems.reduce((sum, entry) => sum + num(entry.orderedQty), 0); const plannedPurchaseQty = num(line.purchaseQty ?? line.shortageQty); return ({ ...line, requiredQty: num(line.requiredQty), onHandQty: num(line.onHandQty), reservedQty: num(line.reservedQty), availableQty: num(line.availableQty), shortageQty: num(line.shortageQty), purchaseToBaseFactor: line.purchaseToBaseFactor == null ? null : num(line.purchaseToBaseFactor), purchaseQty: line.purchaseQty == null ? null : num(line.purchaseQty), lastBaseUnitPrice: line.lastBaseUnitPrice == null ? null : num(line.lastBaseUnitPrice), lastPurchasePrice: line.lastPurchasePrice == null ? null : num(line.lastPurchasePrice), estimatedCost: line.estimatedCost == null ? null : num(line.estimatedCost), orderedQty, orderState: orderedQty <= 0 ? 'NOT_ORDERED' : orderedQty < plannedPurchaseQty ? 'PARTIALLY_ORDERED' : 'FULLY_ORDERED', currentStock: current ? (currentOf.get(line.itemId) ?? { onHand: 0, reserved: 0, available: 0 }) : undefined }); }), summary: summary(detail) };
}
function requirementData(planId: string, lines: Awaited<ReturnType<typeof calculatePurchasePlan>>['requirements']) { return lines.map((line) => ({ purchasePlanId: planId, ...line, requiredQty: D(line.requiredQty), onHandQty: D(line.onHandQty), reservedQty: D(line.reservedQty), availableQty: D(line.availableQty), shortageQty: D(line.shortageQty), purchaseToBaseFactor: line.purchaseToBaseFactor == null ? null : D(line.purchaseToBaseFactor), purchaseQty: line.purchaseQty == null ? null : D(line.purchaseQty), lastBaseUnitPrice: line.lastBaseUnitPrice == null ? null : D(line.lastBaseUnitPrice), lastPurchasePrice: line.lastPurchasePrice == null ? null : D(line.lastPurchasePrice), estimatedCost: line.estimatedCost == null ? null : D(line.estimatedCost), sources: line.sources as Prisma.InputJsonValue })); }
function errorReply(reply: FastifyReply, error: unknown) { if (error instanceof ProductionCalculationError) return reply.status(400).send(fail(error.code, error.message)); const message = error instanceof Error ? error.message : ''; if (message === 'PLAN_NOT_DRAFT') return reply.status(409).send(fail(message, 'แก้ไขหรือคำนวณใหม่ได้เฉพาะแผนร่าง')); if (message === 'VERSION_CONFLICT') return reply.status(409).send(fail(message, 'แผนถูกแก้ไขจากหน้าจออื่น กรุณาโหลดใหม่')); throw error; }

export default async function purchasePlanningRoutes(app: FastifyInstance) {
  app.get('/purchase-planning/lookups', { preHandler: VIEW }, async (req) => { const companyId = req.user.companyId!; const [recipes, warehouses, suppliers, categories] = await Promise.all([prisma.recipe.findMany({ where: { companyId, isActive: true, deletedAt: null, versions: { some: { isActive: true } } }, select: { id: true, code: true, name: true, product: { select: { id: true, code: true, name: true, baseUnit: { select: { code: true } } } }, versions: { where: { isActive: true }, orderBy: { versionNo: 'desc' }, select: { id: true, versionNo: true, yieldMode: true } } }, orderBy: { name: 'asc' } }), prisma.warehouse.findMany({ where: { companyId, isActive: true, deletedAt: null }, select: { id: true, code: true, name: true }, orderBy: { name: 'asc' } }), prisma.supplier.findMany({ where: { companyId, isActive: true, deletedAt: null }, select: { id: true, code: true, name: true }, orderBy: { name: 'asc' } }), prisma.category.findMany({ where: { companyId, isActive: true, deletedAt: null }, select: { id: true, name: true }, orderBy: { name: 'asc' } })]); return ok({ recipes, warehouses, suppliers, categories, reservedBehavior: 'READ_ONLY_NO_AUTOMATIC_RESERVATION' }); });
  app.post('/purchase-planning/preview', { preHandler: CREATE }, async (req, reply) => { try { const body = z.object({ warehouseId: z.string(), targets: z.array(targetInput).min(1) }).parse(req.body); return ok(await calculatePurchasePlan(req.user.companyId!, body.warehouseId, body.targets)); } catch (error) { return errorReply(reply, error); } });
  app.get('/purchase-planning', { preHandler: VIEW }, async (req) => { const q = listInput.parse(req.query); const rows = await prisma.purchasePlan.findMany({ where: { companyId: req.user.companyId!, status: q.status, planDate: q.dateFrom || q.dateTo ? { ...(q.dateFrom ? { gte: new Date(`${q.dateFrom}T00:00:00.000Z`) } : {}), ...(q.dateTo ? { lte: new Date(`${q.dateTo}T23:59:59.999Z`) } : {}) } : undefined, requirements: q.shortageOnly || q.supplierId || q.categoryId ? { some: { shortageQty: q.shortageOnly ? { gt: 0 } : undefined, OR: q.supplierId ? [{ latestSupplierId: q.supplierId }, { selectedSupplierId: q.supplierId }] : undefined, categoryId: q.categoryId } } : undefined }, include, orderBy: { createdAt: 'desc' }, take: 200 }); return ok(await Promise.all(rows.map((row) => serialize(row)))); });
  app.get('/purchase-planning/:id', { preHandler: VIEW }, async (req, reply) => { const { id } = z.object({ id: z.string() }).parse(req.params); const row = await prisma.purchasePlan.findFirst({ where: { id, companyId: req.user.companyId! }, include }); if (!row) return reply.status(404).send(fail('PLAN_NOT_FOUND', 'ไม่พบแผนจัดซื้อ')); return ok(await serialize(row, true)); });
  app.post('/purchase-planning', { preHandler: CREATE }, async (req, reply) => { try { const body = planInput.parse(req.body); const companyId = req.user.companyId!; const calc = await calculatePurchasePlan(companyId, body.warehouseId, body.targets); const id = await withDocumentNumberRetry(() => prisma.$transaction(async (tx) => { const planNo = await nextDocumentNo(tx, companyId, 'PURCHASE_PLAN', body.planDate); const plan = await tx.purchasePlan.create({ data: { companyId, planNo, planDate: body.planDate, warehouseId: body.warehouseId, note: body.note, createdById: req.user.sub, updatedById: req.user.sub } }); await tx.purchasePlanTarget.createMany({ data: calc.targets.map((line) => ({ purchasePlanId: plan.id, ...line, plannedQty: D(line.plannedQty) })) }); await tx.purchasePlanRequirement.createMany({ data: requirementData(plan.id, calc.requirements) }); await tx.auditLog.create({ data: { userId: req.user.sub, companyId, action: 'PURCHASE_PLAN_CREATED', entity: 'PurchasePlan', entityId: plan.id, after: { planNo, targetCount: calc.targets.length } } }); return plan.id; })); return reply.status(201).send(ok(await serialize((await prisma.purchasePlan.findUniqueOrThrow({ where: { id }, include })), true))); } catch (error) { return errorReply(reply, error); } });
  app.patch('/purchase-planning/:id', { preHandler: EDIT }, async (req, reply) => { try { const { id } = z.object({ id: z.string() }).parse(req.params); const body = editInput.parse(req.body); const companyId = req.user.companyId!; const current = await prisma.purchasePlan.findFirst({ where: { id, companyId } }); if (!current) return reply.status(404).send(fail('PLAN_NOT_FOUND', 'ไม่พบแผนจัดซื้อ')); if (current.status !== 'DRAFT') throw new Error('PLAN_NOT_DRAFT'); const calc = await calculatePurchasePlan(companyId, body.warehouseId, body.targets); await prisma.$transaction(async (tx) => { const changed = await tx.purchasePlan.updateMany({ where: { id, companyId, status: 'DRAFT', version: body.version }, data: { planDate: body.planDate, warehouseId: body.warehouseId, note: body.note, updatedById: req.user.sub, version: { increment: 1 } } }); if (changed.count !== 1) throw new Error('VERSION_CONFLICT'); await tx.purchasePlanTarget.deleteMany({ where: { purchasePlanId: id } }); await tx.purchasePlanRequirement.deleteMany({ where: { purchasePlanId: id } }); await tx.purchasePlanTarget.createMany({ data: calc.targets.map((line) => ({ purchasePlanId: id, ...line, plannedQty: D(line.plannedQty) })) }); await tx.purchasePlanRequirement.createMany({ data: requirementData(id, calc.requirements) }); await tx.auditLog.create({ data: { userId: req.user.sub, companyId, action: 'PURCHASE_PLAN_RECALCULATED', entity: 'PurchasePlan', entityId: id, after: { targetCount: calc.targets.length } } }); }); return ok(await serialize(await prisma.purchasePlan.findUniqueOrThrow({ where: { id }, include }), true)); } catch (error) { return errorReply(reply, error); } });
  app.post('/purchase-planning/:id/ready', { preHandler: EDIT }, async (req, reply) => { const { id } = z.object({ id: z.string() }).parse(req.params); const changed = await prisma.purchasePlan.updateMany({ where: { id, companyId: req.user.companyId!, status: 'DRAFT' }, data: { status: 'READY', readyAt: new Date(), updatedById: req.user.sub, version: { increment: 1 } } }); if (!changed.count) return reply.status(409).send(fail('PLAN_NOT_DRAFT', 'ทำพร้อมได้เฉพาะแผนร่าง')); return ok(await serialize(await prisma.purchasePlan.findUniqueOrThrow({ where: { id }, include }), true)); });
  app.post('/purchase-planning/:id/cancel', { preHandler: EDIT }, async (req, reply) => { const { id } = z.object({ id: z.string() }).parse(req.params); const changed = await prisma.purchasePlan.updateMany({ where: { id, companyId: req.user.companyId!, status: { in: ['DRAFT','READY'] } }, data: { status: 'CANCELLED', cancelledAt: new Date(), updatedById: req.user.sub, version: { increment: 1 } } }); if (!changed.count) return reply.status(409).send(fail('PLAN_NOT_ACTIVE', 'แผนนี้ถูกยกเลิกแล้ว')); return ok(await serialize(await prisma.purchasePlan.findUniqueOrThrow({ where: { id }, include }), true)); });
  app.get('/purchase-planning/:id/document.pdf', { preHandler: [VIEW, requirePermission('DOCUMENT_DOWNLOAD')] }, async (req, reply) => { const { id } = z.object({ id: z.string() }).parse(req.params); const companyId = req.user.companyId!; const [plan, company] = await Promise.all([prisma.purchasePlan.findFirst({ where: { id, companyId }, include }), prisma.company.findUnique({ where: { id: companyId } })]); if (!plan || !company) return reply.status(404).send(fail('PLAN_NOT_FOUND', 'ไม่พบแผนจัดซื้อ')); const shortages = plan.requirements.filter((line) => num(line.shortageQty) > 0); const document: BusinessDocument = { type: 'PURCHASE_PLAN', title: 'PURCHASE_PLAN', documentNo: plan.planNo, date: plan.planDate, company: { nameTh: company.nameTh, nameEn: company.nameEn, logoUrl: company.logoUrl, address: company.address, phone: company.phone, email: company.email, taxId: company.taxId, website: company.website, lineId: company.lineId, documentFooter: company.documentFooter }, status: plan.status, subject: [{ label: 'คลัง', value: plan.warehouse.name }, { label: 'รายการผลิต', value: `${plan.targets.length} รายการ` }, { label: 'หมายเหตุเอกสาร', value: 'เอกสารวางแผน — ไม่ใช่ใบสั่งซื้อ' }], lines: shortages.map((line) => ({ name: line.itemName, detail: line.latestSupplierName ? `ผู้ขายล่าสุด: ${line.latestSupplierName}` : 'ไม่มีหลักฐานผู้ขายล่าสุด', quantity: num(line.purchaseQty ?? line.shortageQty), unit: line.purchaseUnitCode ?? line.baseUnitCode, price: line.lastPurchasePrice == null ? undefined : num(line.lastPurchasePrice), total: line.estimatedCost == null ? undefined : num(line.estimatedCost) })), summary: [{ label: 'วัตถุดิบขาด', value: shortages.length }, { label: 'ประมาณการจากราคาล่าสุด', value: shortages.reduce((sum, line) => sum + num(line.estimatedCost), 0) }], note: 'เอกสารวางแผน — ไม่ใช่ใบสั่งซื้อ' }; const pdf = await renderBusinessPdf(document); return reply.header('Content-Type','application/pdf').send(pdf); });
}
