import { FormEvent, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { catalogApi, type CostBreakdown, type MenuRow, type PricingResult, type RecipeDetail, type RecipeRow } from '@/lib/catalog';

export default function FoodCostingPage({section}:{section:'menus'|'recipes'|'costing'}){
 const [menus,setMenus]=useState<MenuRow[]>([]);const[recipes,setRecipes]=useState<RecipeRow[]>([]);const[recipe,setRecipe]=useState<RecipeDetail|null>(null);const[versionId,setVersionId]=useState('');const[cost,setCost]=useState<CostBreakdown|null>(null);const[pricing,setPricing]=useState<PricingResult|null>(null);const[mode,setMode]=useState<'markupPercent'|'marginPercent'|'sellingPrice'>('marginPercent');const[value,setValue]=useState(30);const[priceType,setPriceType]=useState('RETAIL');const[error,setError]=useState('');const[message,setMessage]=useState('');
 const load=()=>Promise.all([catalogApi.menus(),catalogApi.recipes()]).then(([m,r])=>{setMenus(m);setRecipes(r);});useEffect(()=>{void load().catch((e:Error)=>setError(e.message));},[]);
 const selectRecipe=async(id:string)=>{if(!id){setRecipe(null);setVersionId('');setCost(null);return;}try{const d=await catalogApi.recipe(id);setRecipe(d);const active=d.versions.find(v=>v.isActive)??d.versions[0];setVersionId(active?.id??'');if(active)await calculate(active.id);}catch(e){setError(e instanceof Error?e.message:'โหลดสูตรไม่สำเร็จ');}};
 const calculate=async(vId=versionId,e?:FormEvent)=>{e?.preventDefault();setError('');if(!vId)return;try{const result=await catalogApi.calculate({recipeVersionId:vId,[mode]:value});setCost(result.breakdown);setPricing(result.pricing);}catch(err){setError(err instanceof Error?err.message:'คำนวณไม่สำเร็จ');}};
 const save=async()=>{if(!recipe||!pricing)return;setError('');try{await catalogApi.savePrice({itemId:recipe.product.id,priceType,price:pricing.sellingPrice,markupPercent:pricing.markupPercent,marginPercent:pricing.marginPercent});setMessage('บันทึกราคาขายแล้ว');await load();}catch(e){setError(e instanceof Error?e.message:'บันทึกราคาไม่สำเร็จ');}};
 if(section==='costing')return <section className="section"><div className="section-head"><div><h1>Costing Workspace</h1><p>คำนวณจาก Recipe Version และราคาวัตถุดิบจริง</p></div></div>{error&&<div className="error-banner">{error}</div>}{message&&<div className="success-banner">{message}</div>}<form className="card card-pad" onSubmit={e=>void calculate(versionId,e)} style={{display:'grid',gap:12}}><label>สูตร<select onChange={e=>void selectRecipe(e.target.value)}><option value="">เลือกสูตร</option>{recipes.map(r=><option key={r.id} value={r.id}>{r.code} — {r.name}</option>)}</select></label>{recipe&&<label>เวอร์ชัน<select value={versionId} onChange={e=>setVersionId(e.target.value)}>{recipe.versions.map(v=><option key={v.id} value={v.id}>V{v.versionNo}{v.isActive?' (ใช้งาน)':''}</option>)}</select></label>}<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}><label>วิธีกำหนดราคา<select value={mode} onChange={e=>setMode(e.target.value as typeof mode)}><option value="marginPercent">Margin %</option><option value="markupPercent">Markup %</option><option value="sellingPrice">ราคาขาย</option></select></label><label>ค่า<input type="number" step=".01" value={value} onChange={e=>setValue(+e.target.value)}/></label></div>{mode==='marginPercent'&&value>=100&&<p className="error-banner">Margin ต้องต่ำกว่า 100%</p>}<button className="primary-button" disabled={!versionId||mode==='marginPercent'&&value>=100}>คำนวณ</button></form>{cost&&<div className="card card-pad" style={{marginTop:16}}><h2>Cost Breakdown</h2><div className="module-grid"><Metric label="วัตถุดิบ" value={cost.materialCost}/><Metric label="บรรจุภัณฑ์" value={cost.packagingCost}/><Metric label="ค่าแรง" value={cost.laborCost}/><Metric label="สาธารณูปโภค" value={cost.utilityCost}/><Metric label="Overhead" value={cost.overheadCost}/><Metric label="ของเสีย" value={cost.wasteCost}/><Metric label="รวมต่อ Batch" value={cost.totalCost}/><Metric label="ต้นทุนต่อหน่วย" value={cost.unitCost}/></div>{pricing&&<div style={{marginTop:20}}><h2>Pricing Simulator</h2>{pricing.isLoss&&<div className="error-banner">ราคาขายต่ำกว่าต้นทุน</div>}<p>ราคาขาย <strong>{pricing.sellingPrice.toFixed(2)}</strong> · กำไร/หน่วย <strong>{pricing.profit.toFixed(2)}</strong> · Markup {pricing.markupPercent}% · Margin {pricing.marginPercent}%</p><label>ระดับราคา<select value={priceType} onChange={e=>setPriceType(e.target.value)}><option value="RETAIL">Retail</option><option value="WHOLESALE">Wholesale</option><option value="AGENT">Agent</option><option value="SPECIAL">Special</option></select></label><button type="button" className="primary-button" onClick={()=>void save()}>บันทึกราคาขาย</button></div>}</div>}</section>;
 const isMenus=section==='menus';return <section className="section"><div className="section-head"><div><h1>{isMenus?'เมนูอาหาร':'สูตรอาหาร'}</h1><p>ข้อมูลจริงจาก PostgreSQL</p></div><Link className="primary-button" to={isMenus?'/menus/new':'/recipes/new'}>+ เพิ่ม{isMenus?'เมนู':'สูตร'}</Link></div>{error&&<div className="error-banner">{error}</div>}<div className="card card-pad" style={{overflowX:'auto'}}><table><thead><tr><th>รหัส</th><th>ชื่อ</th><th>{isMenus?'สูตร':'เวอร์ชัน'}</th><th>ต้นทุน</th><th>ราคาขาย</th><th>สถานะ</th></tr></thead><tbody>{isMenus?menus.map(m=><tr key={m.id}><td>{m.code}</td><td><Link to={`/menus/${m.id}`}>{m.name}</Link></td><td>{m.hasRecipe?'มีสูตร':'ยังไม่มีสูตร'}</td><td>{m.totalCost?.toFixed(2)??'—'}</td><td>{m.sellingPrice?.toFixed(2)??'—'}</td><td>{m.isActive?'ใช้งาน':'ปิดใช้งาน'}</td></tr>):recipes.map(r=><tr key={r.id}><td>{r.code}</td><td><Link to={`/recipes/${r.id}`}>{r.name}</Link></td><td>{r.versionCount}</td><td>{r.unitCost?.toFixed(4)??'—'}</td><td>—</td><td>{r.isActive?'ใช้งาน':'ปิดใช้งาน'}</td></tr>)}</tbody></table>{(isMenus?menus:recipes).length===0&&<p>ยังไม่มีข้อมูล</p>}</div></section>;
}
function Metric({label,value}:{label:string;value:number}){return <div className="card card-pad"><small>{label}</small><h3>{value.toFixed(2)}</h3></div>}
