import { FormEvent, useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import ImageUpload from '@/components/ui/ImageUpload';
import { catalogApi, type Category, type MenuDetail, type Unit } from '@/lib/catalog';

export default function MenuPage({ mode }: { mode: 'form' | 'detail' }) {
  const { id } = useParams(); const navigate = useNavigate();
  const [menu, setMenu] = useState<MenuDetail | null>(null); const [units,setUnits]=useState<Unit[]>([]); const [categories,setCategories]=useState<Category[]>([]);
  const [form,setForm]=useState({code:'',name:'',categoryId:'',sellingUnitId:'',imageUrl:null as string|null,isActive:true}); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  useEffect(()=>{ void Promise.all([catalogApi.units(),catalogApi.categories(),id?catalogApi.menu(id):Promise.resolve(null)]).then(([u,c,m])=>{setUnits(u);setCategories(c);setMenu(m);if(m)setForm({code:m.code,name:m.name,categoryId:m.categoryId??'',sellingUnitId:m.sellingUnit?.id??'',imageUrl:m.imageUrl,isActive:m.isActive});}).catch((e:Error)=>setError(e.message));},[id]);
  const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const body={...form,categoryId:form.categoryId||null};if(id)await catalogApi.updateMenu(id,body);else{const made=await catalogApi.createMenu(body);navigate(`/menus/${made.id}`);return;}navigate(`/menus/${id}`);}catch(err){setError(err instanceof Error?err.message:'บันทึกไม่สำเร็จ');}finally{setBusy(false);}};
  if(mode==='detail') return <section className="section"><div className="section-head"><div><h1>{menu?.name??'รายละเอียดเมนู'}</h1><p>{menu?.code}</p></div><div style={{display:'flex',gap:8}}>{id&&<><Link className="btn" to={`/menus/${id}/edit`}>แก้ไข</Link><Link className="primary-button" to={`/menus/${id}/recipes/new`}>สร้างสูตร</Link></>}</div></div>{error&&<div className="error-banner">{error}</div>}{menu&&<div className="card card-pad" style={{display:'grid',gridTemplateColumns:'minmax(180px,280px) 1fr',gap:24}}><div>{menu.imageUrl?<img src={menu.imageUrl} alt={menu.name} style={{width:'100%',borderRadius:12}}/>:<div className="empty-state">ไม่มีรูป</div>}</div><dl className="detail-grid"><dt>หมวดหมู่</dt><dd>{menu.category?.name??'—'}</dd><dt>หน่วยขาย</dt><dd>{menu.sellingUnit?.code??'—'}</dd><dt>สูตรใช้งาน</dt><dd>{menu.activeRecipeId?<Link to={`/recipes/${menu.activeRecipeId}`}>V{menu.activeVersionNo}</Link>:'ยังไม่มีสูตร'}</dd><dt>ต้นทุนต่อหน่วย</dt><dd>{menu.currentCost?.toFixed(4)??'—'}</dd><dt>ราคาขาย</dt><dd>{menu.sellingPrice?.toFixed(2)??'—'}</dd><dt>Margin</dt><dd>{menu.margin===null?'—':`${menu.margin}%`}</dd><dt>สถานะ</dt><dd>{menu.isActive?'ใช้งาน':'ปิดใช้งาน'}</dd><dt>สร้างเมื่อ</dt><dd>{new Date(menu.createdAt).toLocaleString('th-TH')}</dd><dt>แก้ไขล่าสุด</dt><dd>{new Date(menu.updatedAt).toLocaleString('th-TH')}</dd></dl></div>}</section>;
  return <section className="section"><div className="section-head"><div><h1>{id?'แก้ไขเมนู':'เพิ่มเมนู'}</h1><p>ข้อมูลจะบันทึกลง PostgreSQL</p></div></div>{error&&<div className="error-banner">{error}</div>}<form className="card card-pad" onSubmit={submit} style={{display:'grid',gap:16,maxWidth:840}}><ImageUpload kind="menus" value={form.imageUrl} onChange={imageUrl=>setForm(f=>({...f,imageUrl}))}/><label>รหัสเมนู<input value={form.code} disabled={Boolean(id)} onChange={e=>setForm(f=>({...f,code:e.target.value}))}/></label><label>ชื่อเมนู<input required value={form.name} onChange={e=>setForm(f=>({...f,name:e.target.value}))}/></label><label>หมวดหมู่<select value={form.categoryId} onChange={e=>setForm(f=>({...f,categoryId:e.target.value}))}><option value="">ไม่ระบุ</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>หน่วยขาย<select required value={form.sellingUnitId} onChange={e=>setForm(f=>({...f,sellingUnitId:e.target.value}))}><option value="">เลือกหน่วย</option>{units.map(u=><option key={u.id} value={u.id}>{u.code} — {u.name}</option>)}</select></label>{id&&<label><input type="checkbox" checked={form.isActive} onChange={e=>setForm(f=>({...f,isActive:e.target.checked}))}/> ใช้งาน</label>}<button className="primary-button" disabled={busy}>{busy?'กำลังบันทึก…':'บันทึก'}</button></form></section>;
}
