import { useState } from 'react';
import { useAuth } from '@/auth/AuthContext';
import PasswordExperience from '@/components/auth/PasswordExperience';
export default function ChangePasswordPage() { return <PasswordExperience />; }
export function LegacyChangePasswordPage() {
  const { changePassword } = useAuth(); const [currentPassword, setCurrent] = useState(''); const [newPassword, setNew] = useState(''); const [confirm, setConfirm] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (newPassword !== confirm) { setError('ยืนยันรหัสผ่านไม่ตรงกัน'); return; } setBusy(true); setError(''); try { await changePassword(currentPassword, newPassword); location.assign('/login'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'เปลี่ยนรหัสผ่านไม่สำเร็จ'); } finally { setBusy(false); } };
  return <div className="center-page"><form className="auth-card compact" onSubmit={(event) => void submit(event)}><img className="form-logo" src="/s2a-logo.png" alt="S2A ERP" /><p className="eyebrow">FIRST LOGIN SECURITY</p><h2>ตั้งรหัสผ่านใหม่</h2><p className="subtle">ต้องมีอย่างน้อย 10 ตัวอักษร พร้อมตัวพิมพ์ใหญ่ พิมพ์เล็ก ตัวเลข และอักขระพิเศษ</p>{error && <div className="alert">{error}</div>}<label>รหัสผ่านปัจจุบัน<input type="password" autoComplete="current-password" value={currentPassword} onChange={(e) => setCurrent(e.target.value)} required /></label><label>รหัสผ่านใหม่<input type="password" autoComplete="new-password" value={newPassword} onChange={(e) => setNew(e.target.value)} required /></label><label>ยืนยันรหัสผ่านใหม่<input type="password" autoComplete="new-password" value={confirm} onChange={(e) => setConfirm(e.target.value)} required /></label><button className="primary-button" disabled={busy}>{busy ? 'กำลังบันทึก...' : 'บันทึกรหัสผ่านใหม่'}</button></form></div>;
}
