import { useEffect, useState, type FormEvent } from 'react';
import { BellRing, Building2, CheckCircle2, FileText, Image, Mail, Save } from 'lucide-react';
import { apiClient } from '@/lib/api-client';
import { useToast } from '@/components/ui/Toast';

type Company = { id:string;code:string;nameTh:string;nameEn?:string;logoUrl?:string;taxId?:string;address?:string;phone?:string;email?:string;website?:string;authorizedName?:string;documentFooter?:string;providers:{email:boolean;line:boolean} };

export default function CompanySettingsPage(){
  const {toast}=useToast();const [company,setCompany]=useState<Company>();const [error,setError]=useState('');const [saved,setSaved]=useState(false);const [dirty,setDirty]=useState(false);const [busy,setBusy]=useState(false);const [logoFailed,setLogoFailed]=useState(false);
  useEffect(()=>{apiClient.get<Company>('/business/company').then(setCompany).catch((e:Error)=>setError(e.message));},[]);
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setSaved(false);const d=new FormData(e.currentTarget);try{const updated=await apiClient.patch<Company>('/business/company',{nameTh:d.get('nameTh'),nameEn:d.get('nameEn')||null,logoUrl:d.get('logoUrl')||null,taxId:d.get('taxId')||null,address:d.get('address')||null,phone:d.get('phone')||null,email:d.get('email')||null,website:d.get('website')||null,authorizedName:d.get('authorizedName')||null,documentFooter:d.get('documentFooter')||null});setCompany({...updated,providers:company?.providers??{email:false,line:false}});setSaved(true);setDirty(false);toast({title:'บันทึกการตั้งค่าสำเร็จ',description:`ข้อมูลบริษัท “${updated.nameTh}” ถูกอัปเดตเรียบร้อยแล้ว`,variant:'success'});}catch(reason){const message=reason instanceof Error?reason.message:'กรุณาตรวจสอบข้อมูลและลองอีกครั้ง';setError(message);toast({title:'ไม่สามารถบันทึกการตั้งค่าได้',description:message,variant:'error',actionLabel:'ลองอีกครั้ง',onAction:()=>setError('')});}finally{setBusy(false);}};
  if(!company)return <div className="company-empty">{error||'กำลังโหลดข้อมูลบริษัท…'}</div>;
  return <section className="settings-page"><header><div><span>COMPANY CONTROL</span><h1>ตั้งค่าบริษัท</h1><p>ข้อมูลอัตลักษณ์ เอกสาร และช่องทางการแจ้งเตือนของพื้นที่ทำงานนี้</p></div><div className="settings-logo">{!logoFailed&&company.logoUrl?<img src={company.logoUrl} onError={()=>setLogoFailed(true)}/>:<strong>KS</strong>}</div></header>{error&&<div className="auth-alert">{error}</div>}{saved&&<div className="settings-success"><CheckCircle2/>บันทึกข้อมูลบริษัทเรียบร้อย</div>}<form onSubmit={(e)=>void submit(e)} onChange={()=>{setDirty(true);setSaved(false)}}><main><section><div className="settings-title"><Building2/><div><h2>ข้อมูลบริษัท</h2><p>ใช้ในส่วนหัว ระบบ และเอกสารธุรกิจ</p></div></div><div className="settings-fields"><label>ชื่อภาษาไทย<input name="nameTh" defaultValue={company.nameTh} required/></label><label>ชื่อภาษาอังกฤษ<input name="nameEn" defaultValue={company.nameEn}/></label><label>Tax ID<input name="taxId" defaultValue={company.taxId}/></label><label>โทรศัพท์<input name="phone" defaultValue={company.phone}/></label><label>Email<input name="email" type="email" defaultValue={company.email}/></label><label>Website<input name="website" defaultValue={company.website}/></label><label className="wide">ที่อยู่<textarea name="address" defaultValue={company.address}/></label></div></section><section><div className="settings-title"><Image/><div><h2>โลโก้บริษัท</h2><p>โลโก้ปัจจุบันแสดงใน Company Selector และเอกสาร</p></div></div><details className="advanced-logo"><summary>การตั้งค่าขั้นสูง</summary><div className="settings-fields"><label className="wide">Public Logo URL<input name="logoUrl" defaultValue={company.logoUrl??'/company-logos/krua-suesoddee.png'}/><small>ไม่รองรับการอัปโหลดไฟล์โดยตรงเพื่อความปลอดภัย</small></label></div></details></section><section><div className="settings-title"><FileText/><div><h2>ข้อมูลเอกสาร</h2><p>ข้อมูลผู้มีอำนาจและข้อความท้ายเอกสาร</p></div></div><div className="settings-fields"><label>ผู้มีอำนาจลงนาม<input name="authorizedName" defaultValue={company.authorizedName}/></label><label className="wide">ข้อความท้ายเอกสาร<textarea name="documentFooter" defaultValue={company.documentFooter}/></label></div></section></main><aside><small>INTEGRATION STATUS</small><h2>ช่องทางแจ้งเตือน</h2><article><Mail/><div><strong>Email</strong><span>{company.providers.email?'พร้อมใช้งาน':'ยังไม่ได้ตั้งค่าการส่งอีเมล'}</span></div><i className={company.providers.email?'on':''}/></article><article><BellRing/><div><strong>LINE</strong><span>{company.providers.line?'พร้อมใช้งาน':'ยังไม่ได้ตั้งค่า LINE Notification'}</span></div><i className={company.providers.line?'on':''}/></article><p>ระบบหลักและ Web Notification ยังคงใช้งานได้ แม้ช่องทางภายนอกยังไม่ตั้งค่า</p>{dirty&&<div className="settings-dirty">ยังไม่ได้บันทึก</div>}<button disabled={busy||!dirty}><Save/>{busy?'กำลังบันทึก...':dirty?'บันทึกการตั้งค่า':'บันทึกแล้ว'}</button></aside></form></section>;
}
