import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, Download, GitCompareArrows, Info, Scale, TrendingUp } from 'lucide-react';
import { apiClient } from '@/lib/api-client';
import { ContentCard, KPICard, KPIGrid, PageContainer, PageHeader } from '@/components/layout/page';
import { quantity } from '@/lib/presentation';

type Version={id:string;versionNo:number;createdAt:string;costs:{totalCost:number}[]};type Recipe={id:string;code:string;name:string;versions:Version[]};
type Line={itemId:string;itemName:string;unitCode:string;status:string;comparable:boolean;previousQty:number|null;currentQty:number|null;previousLineCost:number|null;currentLineCost:number|null;priceEffect:number|null;quantityEffect:number|null;interactionEffect:number|null;netContribution:number|null};
type Comparison={from:{id:string;versionNo:number};to:{id:string;versionNo:number};summary:{previousComparableCost:number;currentComparableCost:number;change:number;changePercent:number|null;priceEffect:number;quantityEffect:number;interactionEffect:number;compositionEffect:number;reconciled:boolean;comparableLineCount:number;unavailableLineCount:number;coveragePercent:number};lines:Line[]};
type Production={id:string;orderNo:string;date:string;recipe?:{name:string};product:{name:string};standardCost:number;actualCost:number;variance:number;variancePercent:number|null;recordedWasteCost:number;uncostedWasteCount:number;materials:{itemId:string;itemName:string;expectedQty:number;actualQty:number;unitCode:string;usageContribution:number}[]};
type Purchase={receiptId:string;receiptNo:string;receiptDate:string;poNo?:string;supplierName?:string;itemId:string;itemName:string;receivedBaseQty:number;baseUnitPriceOrdered:number;baseUnitPriceActual:number;variancePerBaseUnit:number;totalVariance:number};
type Mover={itemId:string;itemCode:string;itemName:string;unitCode:string;previous:{at:string;cost:number};latest:{at:string;cost:number;source:string};change:number;changePercent:number|null;observationCount:number;lowSample:boolean};
const money=(v:number|null|undefined)=>v==null?'ไม่พร้อมคำนวณ':`${v>=0?'':'-'}฿${Math.abs(v).toLocaleString('th-TH',{minimumFractionDigits:2,maximumFractionDigits:2})}`;const signed=(v:number|null)=>v==null?'—':`${v>=0?'+':''}${money(v)}`;

export default function CostVariancePage(){const[recipes,setRecipes]=useState<Recipe[]>([]),[recipeId,setRecipeId]=useState(''),[fromId,setFromId]=useState(''),[toId,setToId]=useState(''),[comparison,setComparison]=useState<Comparison>(),[production,setProduction]=useState<Production[]>([]),[purchase,setPurchase]=useState<Purchase[]>([]),[movers,setMovers]=useState<Mover[]>([]),[error,setError]=useState('');
useEffect(()=>{void Promise.allSettled([apiClient.get<Recipe[]>('/business/analytics/cost-variance/recipes').then(x=>{setRecipes(x);const r=x.find(y=>y.versions.length>1);if(r){setRecipeId(r.id);setFromId(r.versions.at(-2)!.id);setToId(r.versions.at(-1)!.id)}}),apiClient.get<Production[]>('/business/analytics/cost-variance/production').then(setProduction),apiClient.get<Purchase[]>('/business/analytics/cost-variance/purchase').then(setPurchase),apiClient.get<Mover[]>('/business/analytics/cost-variance/item-movers').then(setMovers)])},[]);
useEffect(()=>{if(!fromId||!toId)return;apiClient.get<Comparison>(`/business/analytics/cost-variance/recipe-comparison?fromVersionId=${fromId}&toVersionId=${toId}`).then(setComparison).catch((e:Error)=>setError(e.message))},[fromId,toId]);
const versions=useMemo(()=>recipes.find(x=>x.id===recipeId)?.versions??[],[recipes,recipeId]);const prodTotal=production.reduce((s,x)=>s+x.variance,0),purchaseTotal=purchase.reduce((s,x)=>s+x.totalVariance,0);const selectRecipe=(id:string)=>{setRecipeId(id);const v=recipes.find(x=>x.id===id)?.versions??[];setFromId(v.at(-2)?.id??'');setToId(v.at(-1)?.id??'')};
return <PageContainer size="wide" className="analytics-page"><PageHeader breadcrumb="วิเคราะห์ต้นทุน" title="อธิบายผลต่างต้นทุน" description="แสดงการแยกองค์ประกอบทางคณิตศาสตร์จากหลักฐานจริง ไม่สรุปเหตุผลทางธุรกิจแทนผู้ใช้"/>{error&&<div className="alert error">{error}</div>}<KPIGrid columns={4}><KPICard label="สูตรที่เปรียบเทียบ" value={comparison?1:0} icon={<GitCompareArrows/>}/><KPICard label="ผลต่างการผลิตจริง" value={money(prodTotal)} icon={<Scale/>}/><KPICard label="PO เทียบรับจริง" value={money(purchaseTotal)} icon={<TrendingUp/>}/><KPICard label="รายการต้นทุนเคลื่อนไหว" value={movers.length}/></KPIGrid>
<ContentCard title={<>วิเคราะห์การเปลี่ยนแปลงต้นทุน <small className="cv-title-en">Recipe Changes</small></>} description="เทียบสูตรสองเวอร์ชัน แยกผลจากราคา ปริมาณ และการเพิ่ม/ตัดวัตถุดิบออกจากกัน">
  {/* แถบควบคุมเดียว: เลือกสูตร → เวอร์ชันต้นทาง → เวอร์ชันปลายทาง → ส่งออก
      เดิมทั้งสี่ตัวลอยอยู่ใน .filter-bar โดยไม่มีความสัมพันธ์ทางสายตา */}
  <div className="cv-toolbar">
    <label className="cv-control cv-control--recipe"><span>สูตรอาหาร</span>
      <select value={recipeId} onChange={e=>selectRecipe(e.target.value)}><option value="">เลือกสูตร</option>{recipes.map(r=><option key={r.id} value={r.id}>{r.code} · {r.name}</option>)}</select>
    </label>
    <label className="cv-control"><span>เวอร์ชันก่อนหน้า</span>
      <select value={fromId} onChange={e=>setFromId(e.target.value)}>{versions.map(v=><option key={v.id} value={v.id}>Version {v.versionNo}</option>)}</select>
    </label>
    <span className="cv-arrow" aria-hidden><ArrowRight /></span>
    <label className="cv-control"><span>เวอร์ชันปัจจุบัน</span>
      <select value={toId} onChange={e=>setToId(e.target.value)}>{versions.map(v=><option key={v.id} value={v.id}>Version {v.versionNo}</option>)}</select>
    </label>
    {comparison&&<button className="btn cv-export" onClick={()=>void apiClient.download(`/business/analytics/cost-variance/export.xlsx?section=recipe&fromVersionId=${fromId}&toVersionId=${toId}`,{expect:'xlsx',fallbackName:'recipe-cost-variance.xlsx'})}><Download/>Excel</button>}
  </div>
  {/* สูตรคำนวณเป็นข้อมูลอ้างอิง ไม่ควรเด่นกว่าตัวเลขจริงบนหน้า */}
  <p className="cv-formula" title="Q0(P1−P0) + P0(Q1−Q0) + (Q1−Q0)(P1−P0)"><Info aria-hidden width={14} />วิธีคิด: ผลจากราคา + ผลจากปริมาณ + ผลร่วม โดยแยกการเพิ่ม/ตัดวัตถุดิบออกต่างหาก</p>{comparison?<><div className="cv-metrics">
  <div className="cv-metric"><span>ต้นทุนก่อนหน้า</span><b>{money(comparison.summary.previousComparableCost)}</b></div>
  <div className="cv-metric"><span>ต้นทุนปัจจุบัน</span><b>{money(comparison.summary.currentComparableCost)}</b></div>
  <div className={`cv-metric${comparison.summary.change>0?' is-up':comparison.summary.change<0?' is-down':''}`}><span>ผลต่างสุทธิ</span><b>{signed(comparison.summary.change)}</b></div>
  <div className="cv-metric"><span>ความครอบคลุมข้อมูล <small>Coverage</small></span><b>{comparison.summary.coveragePercent.toFixed(2)}%</b></div>
</div><div className="analytics-bars"><div className="breakdown-row"><b>ต้นทุนก่อนหน้า</b><span>{money(comparison.summary.previousComparableCost)}</span></div><div className="breakdown-row"><b>ผลจากราคา <small>Price</small></b><span>{signed(comparison.summary.priceEffect)}</span></div><div className="breakdown-row"><b>ผลจากปริมาณ <small>Quantity</small></b><span>{signed(comparison.summary.quantityEffect)}</span></div><div className="breakdown-row"><b>ผลร่วม <small>Interaction</small></b><span>{signed(comparison.summary.interactionEffect)}</span></div><div className="breakdown-row"><b>เพิ่ม/ตัดวัตถุดิบ</b><span>{signed(comparison.summary.compositionEffect)}</span></div><div className="breakdown-row"><b>ต้นทุนปัจจุบัน</b><span>{money(comparison.summary.currentComparableCost)}</span><small>{comparison.summary.reconciled?'Reconciled':'ตรวจสอบ reconciliation'} · unavailable {comparison.summary.unavailableLineCount}</small></div></div><div className="table-wrap"><table className="data-table"><thead><tr><th>วัตถุดิบ</th><th>ก่อน / ปัจจุบัน</th><th>Price</th><th>Quantity</th><th>Interaction</th><th>Net</th><th>องค์ประกอบ</th></tr></thead><tbody>{comparison.lines.map(x=><tr key={x.itemId}><td>{x.itemName}<small className="cell-sub">{x.unitCode}</small></td><td className="num">{quantity(x.previousQty)} / {quantity(x.currentQty)}</td><td>{signed(x.priceEffect)}</td><td>{signed(x.quantityEffect)}</td><td>{signed(x.interactionEffect)}</td><td>{signed(x.netContribution)}</td><td>{x.comparable?(x.status==='ADDED'?'เพิ่มวัตถุดิบ':x.status==='REMOVED'?'ตัดวัตถุดิบออก':'เปรียบเทียบได้'):'COST HISTORY INCOMPLETE'}</td></tr>)}</tbody></table></div></>:<p className="production-empty">ต้องมีสูตรอย่างน้อยสองเวอร์ชันและหลักฐานต้นทุนตามวันที่</p>}</ContentCard>
<ContentCard title="Production Variance" description="ผลกระทบจากการใช้จริงเทียบมาตรฐาน; ของเสียที่บันทึกจริงแสดงแยก"><button className="btn" onClick={()=>void apiClient.download('/business/analytics/cost-variance/export.xlsx?section=production',{expect:'xlsx',fallbackName:'production-cost-variance.xlsx'})}><Download/>Excel</button><div className="table-wrap"><table className="data-table"><thead><tr><th>ใบผลิต</th><th>มาตรฐาน</th><th>จริง</th><th>ผลต่าง</th><th>ของเสียที่บันทึก</th><th>ตัวขับหลัก</th></tr></thead><tbody>{production.map(x=><tr key={x.id}><td>{x.orderNo}<small className="cell-sub">{x.recipe?.name??x.product.name}</small></td><td>{money(x.standardCost)}</td><td>{money(x.actualCost)}</td><td>{signed(x.variance)}</td><td>{money(x.recordedWasteCost)}{x.uncostedWasteCount?` · ไม่ทราบต้นทุน ${x.uncostedWasteCount}`:''}</td><td>{x.materials[0]?`${x.materials[0].itemName} ${signed(x.materials[0].usageContribution)}`:'—'}</td></tr>)}</tbody></table></div>{!production.length&&<p className="production-empty">ยังไม่มีใบผลิตที่เสร็จสมบูรณ์</p>}</ContentCard>
<ContentCard title="Purchase Price Variance" description="ราคา PO เทียบใบรับของที่ยืนยันแล้วและเชื่อมเอกสารจริง"><button className="btn" onClick={()=>void apiClient.download('/business/analytics/cost-variance/export.xlsx?section=purchase',{expect:'xlsx',fallbackName:'purchase-price-variance.xlsx'})}><Download/>Excel</button><div className="table-wrap"><table className="data-table"><thead><tr><th>PO / ใบรับ</th><th>ผู้จำหน่าย</th><th>สินค้า</th><th>PO</th><th>รับจริง</th><th>ผลต่างรวม</th></tr></thead><tbody>{purchase.map((x,i)=><tr key={`${x.receiptId}-${x.itemId}-${i}`}><td>{x.poNo??'—'} / {x.receiptNo}</td><td>{x.supplierName??'—'}</td><td>{x.itemName}</td><td>{money(x.baseUnitPriceOrdered)}</td><td>{money(x.baseUnitPriceActual)}</td><td>{signed(x.totalVariance)}</td></tr>)}</tbody></table></div>{purchase.length<3&&<p className="dash-note">ข้อมูลยังมีจำนวนน้อย โปรดอ่านเป็นข้อสังเกตจากเอกสาร ไม่ใช่แนวโน้ม</p>}</ContentCard>
<ContentCard title="Item Cost Movers" description="สองจุดคือการเปรียบเทียบ ไม่เรียกว่าแนวโน้ม"><button className="btn" onClick={()=>void apiClient.download('/business/analytics/cost-variance/export.xlsx?section=movers',{expect:'xlsx',fallbackName:'item-cost-movers.xlsx'})}><Download/>Excel</button><div className="table-wrap"><table className="data-table"><thead><tr><th>สินค้า</th><th>ก่อนหน้า</th><th>ล่าสุด</th><th>ผลต่าง</th><th>แหล่งล่าสุด</th><th>ตัวอย่าง</th></tr></thead><tbody>{movers.map(x=><tr key={x.itemId}><td>{x.itemName}<small className="cell-sub">{x.itemCode} · {x.unitCode}</small></td><td>{money(x.previous.cost)}</td><td>{money(x.latest.cost)}</td><td>{signed(x.change)} {x.changePercent==null?'':`(${x.changePercent.toFixed(2)}%)`}</td><td>{x.latest.source}</td><td>{x.lowSample?'ข้อมูลน้อย':x.observationCount}</td></tr>)}</tbody></table></div></ContentCard></PageContainer>}
