import { useEffect, useState, type FormEvent } from 'react';
import { CalendarDays, FileDown, PackageCheck, Plus, Send, TrendingUp, Users } from 'lucide-react';
import { apiClient } from '@/lib/api-client';

type Customer = { id: string; code: string; name: string; contactName?: string; phone?: string; email?: string; address?: string; orderCount?: number; deliveredSales?: string; upcomingOrders?: number; lastOrder?: { orderNo:string; deliveryDate:string; status:string } };
type Order = { id: string; orderNo: string; status: string; deliveryDate: string; deliveryTime?: string; totalAmount: string; customer: Customer; items: { id: string; menuNameSnapshot: string; quantity: string }[] };
const statusThai: Record<string,string> = { DRAFT:'ร่าง',CONFIRMED:'ยืนยันแล้ว',SENT_TO_PREP:'ส่งให้เตรียม',PICKING:'กำลังเบิก/เตรียม',ISSUED:'เบิกแล้ว',READY:'พร้อมส่ง',DELIVERED:'ส่งสำเร็จ',CANCELLED:'ยกเลิก' };
const openDocument=async(path:string)=>{const blob=await apiClient.blob(path);const url=URL.createObjectURL(blob);window.open(url,'_blank','noopener,noreferrer');window.setTimeout(()=>URL.revokeObjectURL(url),60000);};

export default function OrdersPage() {
  const [orders,setOrders]=useState<Order[]>([]); const [customers,setCustomers]=useState<Customer[]>([]); const [loading,setLoading]=useState(true); const [form,setForm]=useState(false); const [error,setError]=useState('');
  const load=async()=>{setLoading(true);try{const [orderData,customerData]=await Promise.all([apiClient.get<Order[]>('/business/orders'),apiClient.get<Customer[]>('/business/customers')]);setOrders(orderData);setCustomers(customerData);}catch(reason){setError(reason instanceof Error?reason.message:'โหลดข้อมูลไม่สำเร็จ');}finally{setLoading(false);}};
  useEffect(()=>{void load();},[]);
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);setError('');try{await apiClient.post('/business/orders',{customerId:data.get('customerId'),deliveryDate:data.get('deliveryDate'),deliveryTime:data.get('deliveryTime'),note:data.get('note'),idempotencyKey:crypto.randomUUID(),items:[{menuId:String(data.get('menuId')),menuNameSnapshot:String(data.get('menuName')),quantity:Number(data.get('quantity')),unit:String(data.get('unit')),unitPrice:Number(data.get('unitPrice'))}]});setForm(false);await load();}catch(reason){setError(reason instanceof Error?reason.message:'บันทึกไม่สำเร็จ');}};
  const send=async(id:string,status:string)=>{const next=status==='DRAFT'?'CONFIRMED':'SENT_TO_PREP';await apiClient.post(`/business/orders/${id}/transition`,{status:next});await load();};
  const today=new Date().toISOString().slice(0,10);const todayOrders=orders.filter((o)=>o.deliveryDate.slice(0,10)===today);const pending=orders.filter((o)=>!['DELIVERED','CANCELLED'].includes(o.status));const delivered=orders.filter((o)=>o.status==='DELIVERED');
  return <section className="business-page order-workspace"><header><div><span>ORDER & DELIVERY CONTROL</span><h1>ออเดอร์ลูกค้า</h1><p>จัดการกำหนดส่ง รายการ ยอดเงิน และสถานะการเตรียม</p></div><button onClick={()=>setForm(true)}><Plus/>สร้างออเดอร์</button></header><div className="order-kpis"><article><CalendarDays/><span>ส่งวันนี้</span><strong>{todayOrders.length}</strong></article><article><PackageCheck/><span>รอเตรียม/ส่ง</span><strong>{pending.length}</strong></article><article><TrendingUp/><span>ยอดรอส่ง</span><strong>฿{pending.reduce((s,o)=>s+Number(o.totalAmount),0).toLocaleString('th-TH')}</strong></article><article><TrendingUp/><span>ยอดขายจริง</span><strong>฿{delivered.reduce((s,o)=>s+Number(o.totalAmount),0).toLocaleString('th-TH')}</strong></article></div>{error&&<div className="auth-alert">{error}</div>}
    {form&&<form className="business-form" onSubmit={(event)=>void submit(event)}><h2>ออเดอร์ใหม่</h2><label>ลูกค้า<select name="customerId" required><option value="">เลือกลูกค้า</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>วันที่ส่ง<input name="deliveryDate" type="date" required/></label><label>เวลาส่ง<input name="deliveryTime" type="time"/></label><label>รหัสเมนู<input name="menuId" required/></label><label>ชื่อเมนู<input name="menuName" required/></label><label>จำนวน<input name="quantity" type="number" min="0.0001" step="0.0001" required/></label><label>หน่วย<input name="unit" defaultValue="กล่อง" required/></label><label>ราคาต่อหน่วย<input name="unitPrice" type="number" min="0" step="0.01" required/></label><label className="wide">หมายเหตุ<textarea name="note"/></label><div className="wide form-actions"><button type="button" className="secondary" onClick={()=>setForm(false)}>ยกเลิก</button><button>บันทึกร่าง</button></div></form>}
    {loading?<div className="company-empty">กำลังโหลดออเดอร์…</div>:orders.length===0?<div className="business-empty"><CalendarDays/><h2>ยังไม่มีออเดอร์</h2><p>สร้างออเดอร์จริงรายการแรกเพื่อเริ่มวางแผนการเตรียม</p></div>:<div className="business-table"><div className="business-row head"><span>เลขที่</span><span>ลูกค้า</span><span>กำหนดส่ง</span><span>ยอดเงิน</span><span>สถานะ</span><span>จัดการ</span></div>{orders.map(order=><div className="business-row" key={order.id}><strong>{order.orderNo}</strong><span>{order.customer.name}</span><span>{new Date(order.deliveryDate).toLocaleDateString('th-TH')} {order.deliveryTime}</span><span>฿{Number(order.totalAmount).toLocaleString('th-TH')}</span><span className={`order-status ${order.status.toLowerCase()}`}>{statusThai[order.status]??order.status}</span><span className="order-row-actions">{['DRAFT','CONFIRMED'].includes(order.status)&&<button className="row-action" onClick={()=>void send(order.id,order.status)}><Send/>{order.status==='DRAFT'?'ยืนยัน':'ส่งเตรียม'}</button>}<button className="row-action" onClick={()=>void openDocument(`/business/documents/ORDER_SLIP/${order.id}.pdf`)}><FileDown/>PDF</button></span></div>)}</div>}
  </section>;
}

export function CustomersPage(){const [items,setItems]=useState<Customer[]>([]);const [error,setError]=useState('');const load=()=>apiClient.get<Customer[]>('/business/customers').then(setItems).catch((e:Error)=>setError(e.message));useEffect(()=>{void load();},[]);const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);await apiClient.post('/business/customers',{code:d.get('code'),name:d.get('name'),contactName:d.get('contactName'),phone:d.get('phone'),email:d.get('email')});e.currentTarget.reset();await load();};return <section className="business-page customer-workspace"><header><div><span>CUSTOMER INTELLIGENCE</span><h1>ลูกค้า</h1><p>ข้อมูลติดต่อ ออเดอร์ล่วงหน้า และยอดขายจริงจากออเดอร์ที่ส่งสำเร็จ</p></div><Users/></header>{error&&<div className="auth-alert">{error}</div>}<form className="customer-inline" onSubmit={(e)=>void submit(e)}><input name="code" placeholder="รหัสลูกค้า" required/><input name="name" placeholder="ชื่อลูกค้า / โรงเรียน" required/><input name="contactName" placeholder="ผู้ติดต่อ"/><input name="phone" placeholder="โทรศัพท์"/><input name="email" type="email" placeholder="Email"/><button><Plus/>เพิ่มลูกค้า</button></form><div className="customer-grid rich">{items.map(c=><article key={c.id}><div className="customer-card-head"><b>{c.name.slice(0,2).toUpperCase()}</b><div><small>{c.code}</small><h3>{c.name}</h3></div><span>ใช้งาน</span></div><dl><div><dt>ผู้ติดต่อ</dt><dd>{c.contactName||'—'}</dd></div><div><dt>โทรศัพท์</dt><dd>{c.phone||'—'}</dd></div><div><dt>Email</dt><dd>{c.email||'—'}</dd></div><div><dt>ออเดอร์ทั้งหมด</dt><dd>{c.orderCount??0}</dd></div><div><dt>ออเดอร์ล่วงหน้า</dt><dd>{c.upcomingOrders??0}</dd></div><div><dt>ยอดขายจริง</dt><dd>฿{Number(c.deliveredSales??0).toLocaleString('th-TH')}</dd></div></dl>{c.lastOrder&&<footer>ล่าสุด {c.lastOrder.orderNo} · {new Date(c.lastOrder.deliveryDate).toLocaleDateString('th-TH')}</footer>}</article>)}</div>{items.length===0&&<div className="business-empty"><Users/><h2>ยังไม่มีข้อมูลลูกค้า</h2></div>}</section>}
