import { useState, type FormEvent } from 'react';
import { ArrowLeft, CheckCircle2, KeyRound, LoaderCircle, LockKeyhole, MailQuestion, ShieldCheck } from 'lucide-react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { apiClient } from '@/lib/api-client';
import { useToast } from '@/components/ui/Toast';
import LanguageSwitcher from '@/components/LanguageSwitcher';
import { useI18n } from '@/i18n/i18n';

const NEUTRAL = 'หากข้อมูลตรงกับบัญชีในระบบ เราได้เริ่มขั้นตอนรีเซ็ตรหัสผ่านให้แล้ว กรุณาติดต่อผู้ดูแลระบบเพื่อดำเนินการต่อ';

export function ForgotPasswordPage() {
  // Context messages keep this screen synchronized when the locale changes.
  const { locale, messages } = useI18n(); const text = locale === 'en' ? { title:'Forgot password', intro:'Enter your username or email to begin the password reset process.', identifier:'Username or Email', submit:'Continue', busy:'Processing...', complete:'Check the next step', neutral:'If the information matches an account, the password reset process has started. Contact your administrator to continue.', safety:'For security, this message is the same whether or not the account exists.', back:'Back to Sign in' } : locale === 'zh-CN' ? { title:'忘记密码', intro:'请输入用户名或电子邮箱以开始密码重置流程。', identifier:'用户名或电子邮箱', submit:'继续', busy:'正在处理...', complete:'请查看后续步骤', neutral:'如果信息与系统账户匹配，密码重置流程已开始。请联系管理员继续。', safety:'为保障安全，无论账户是否存在，系统均显示相同提示。', back:'返回登录' } : { title:'ลืมรหัสผ่าน', intro:'กรอกชื่อผู้ใช้หรืออีเมลที่ใช้ในระบบ เพื่อเริ่มขั้นตอนรีเซ็ตรหัสผ่าน', identifier:'Username หรือ Email', submit:'ดำเนินการต่อ', busy:'กำลังดำเนินการ...', complete:'ตรวจสอบขั้นตอนต่อไป', neutral:NEUTRAL, safety:'เพื่อความปลอดภัย ข้อความนี้จะเหมือนกันไม่ว่าบัญชีจะมีอยู่หรือไม่', back:'กลับไปเข้าสู่ระบบ' };
  void messages;
  const [identifier, setIdentifier] = useState(''); const [busy, setBusy] = useState(false); const [complete, setComplete] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { await apiClient.post('/auth/forgot-password', { identifier }, { token: null }); } finally { setBusy(false); setComplete(true); } };
  return <main className="recovery-shell"><section className="recovery-card"><div className="recovery-toolbar"><Link to="/login" className="login-back"><ArrowLeft /> {text.back}</Link><LanguageSwitcher compact /></div><span className="recovery-icon">{complete ? <CheckCircle2 /> : <MailQuestion />}</span>{complete ? <><h1>{text.complete}</h1><p>{text.neutral}</p><div className="recovery-note"><ShieldCheck />{text.safety}</div><Link className="auth-submit" to="/login">{text.back}</Link></> : <><small>ACCOUNT RECOVERY</small><h1>{text.title}</h1><p>{text.intro}</p><form onSubmit={(event) => void submit(event)}><label>{text.identifier}<div className="auth-input"><KeyRound /><input autoFocus required value={identifier} onChange={(event) => setIdentifier(event.target.value)} autoComplete="username" /></div></label><button className="auth-submit" disabled={busy}>{busy ? <><LoaderCircle className="spin" />{text.busy}</> : text.submit}</button></form></>}</section></main>;
}

export function ResetPasswordPage() {
  const { locale } = useI18n(); const resetText = locale === 'en' ? { back:'Back to Sign in', title:'Set a new password', intro:'Use at least 10 characters with uppercase, lowercase, a number, and a special character.', password:'New Password', confirm:'Confirm Password', submit:'Set New Password', busy:'Saving...' } : locale === 'zh-CN' ? { back:'返回登录', title:'设置新密码', intro:'密码至少 10 位，并包含大写字母、小写字母、数字和特殊字符。', password:'新密码', confirm:'确认密码', submit:'设置新密码', busy:'正在保存...' } : { back:'กลับไปเข้าสู่ระบบ', title:'ตั้งรหัสผ่านใหม่', intro:'รหัสผ่านใหม่ต้องมีอย่างน้อย 10 ตัว และประกอบด้วยตัวพิมพ์เล็ก ตัวพิมพ์ใหญ่ ตัวเลข และอักขระพิเศษ', password:'รหัสผ่านใหม่', confirm:'ยืนยันรหัสผ่าน', submit:'ตั้งรหัสผ่านใหม่', busy:'กำลังบันทึก...' };
  const [params] = useSearchParams(); const navigate = useNavigate(); const { toast } = useToast(); const token = params.get('token') ?? '';
  const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const valid = password.length >= 10 && /[a-z]/.test(password) && /[A-Z]/.test(password) && /\d/.test(password) && /[^A-Za-z0-9]/.test(password);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!valid) { setError('รหัสผ่านยังไม่ครบตามเงื่อนไข'); return; } if (password !== confirm) { setError('รหัสผ่านทั้งสองช่องไม่ตรงกัน'); return; } setBusy(true); setError(''); try { await apiClient.post('/auth/reset-password', { token, newPassword: password }, { token: null }); toast({ title: 'ตั้งรหัสผ่านใหม่สำเร็จ', description: 'เข้าสู่ระบบด้วยรหัสผ่านใหม่ได้แล้ว', variant: 'success' }); navigate('/login', { replace: true }); } catch (reason) { setError(reason instanceof Error ? reason.message : 'ลิงก์รีเซ็ตไม่ถูกต้องหรือหมดอายุ'); } finally { setBusy(false); } };
  return <main className="recovery-shell"><section className="recovery-card"><div className="recovery-toolbar"><Link to="/login" className="login-back"><ArrowLeft /> {resetText.back}</Link><LanguageSwitcher compact /></div><span className="recovery-icon"><LockKeyhole /></span><small>SECURE PASSWORD RESET</small><h1>{resetText.title}</h1><p>{resetText.intro}</p>{!token && <div className="auth-alert">ไม่พบรหัสยืนยันในลิงก์นี้</div>}{error && <div className="auth-alert" role="alert">{error}</div>}<form onSubmit={(event) => void submit(event)}><label>{resetText.password}<div className="auth-input"><LockKeyhole /><input type="password" autoFocus required minLength={10} value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="new-password" /></div></label><label>{resetText.confirm}<div className="auth-input"><ShieldCheck /><input type="password" required minLength={10} value={confirm} onChange={(event) => setConfirm(event.target.value)} autoComplete="new-password" /></div></label><div className={`recovery-strength ${valid ? 'ready' : ''}`}>{valid ? 'Password policy passed' : '10+ characters • A–Z • a–z • 0–9 • symbol'}</div><button className="auth-submit" disabled={busy || !token}>{busy ? <><LoaderCircle className="spin" />{resetText.busy}</> : resetText.submit}</button></form></section></main>;
}
