import {useEffect,useMemo,useState} from 'react';
import {Download,RotateCcw,TriangleAlert,FlaskConical} from 'lucide-react';
import {apiClient} from '@/lib/api-client';
import {ContentCard,KPICard,KPIGrid,PageContainer,PageHeader,StickySummary,EmptyState} from '@/components/layout/page';
import {GuidanceCard,HelpTip,StatusChip} from '@/components/GuidanceCard';
import {displayEnum,displayPriceType,displayUnit,money,quantity} from '@/lib/presentation';
type Recipe={id:string;code:string;name:string;versions:{id:string;versionNo:number}[]};type Override={itemId:string;unitCost?:number;unitCostPercent?:number;quantity?:number;quantityPercent?:number};type Payload={recipeVersionId:string;ingredientOverrides:Override[];yieldQty?:number;sellingPrices:Record<string,number>;targetMarginPercent?:number;targetMarkupPercent?:number};type Metric={sellingPrice:number;grossProfit:number;marginPercent:number|null;markupPercent:number|null;isLoss:boolean};type Result={recipe:{name:string};version:{versionNo:number;yieldMode:string;yieldUnit?:{code:string;name?:string}|null};coverage:{known:number;eligible:number;percent:number;complete:boolean};baseline:{unitCost:number;effectiveYield:number};simulated:{unitCost:number;effectiveYield:number;costChange:number};lines:{itemId:string;itemName:string;unitCode:string;baselineQuantity:number;simulatedQuantity:number;baselineUnitCost:number|null;simulatedUnitCost:number|null;impact:number|null;costStatus:string;costSource:string;manualCost:boolean}[];tiers:{priceType:string;baseline:Metric|null;simulated:Metric|null}[];targets:{margin:{rawSellingPrice:number}|null;markup:{rawSellingPrice:number}|null;breakEvenSellingPrice:number};bridge:{ingredientImpactPerUnit:number;yieldImpactPerUnit:number;interactionResidual:number};warnings:string[]};
export default function ProfitSimulatorPage(){
 const[recipes,setRecipes]=useState<Recipe[]>([]),[recipeId,setRecipeId]=useState(''),[versionId,setVersionId]=useState('');const[overrides,setOverrides]=useState<Override[]>([]),[prices,setPrices]=useState<Record<string,number>>({}),[yieldQty,setYieldQty]=useState<number>(),[margin,setMargin]=useState<number>(),[markup,setMarkup]=useState<number>();const[result,setResult]=useState<Result>(),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const versions=useMemo(()=>recipes.find(x=>x.id===recipeId)?.versions??[],[recipes,recipeId]);const payload:Payload={recipeVersionId:versionId,ingredientOverrides:overrides,yieldQty,sellingPrices:prices,targetMarginPercent:margin,targetMarkupPercent:markup};
 const calculate=async(next=payload)=>{if(!next.recipeVersionId)return;setBusy(true);setError('');try{setResult(await apiClient.post<Result>('/business/analytics/profit-simulator/calculate',next))}catch(e){setError(e instanceof Error?e.message:'ไม่สามารถคำนวณได้ กรุณาตรวจสอบค่าที่กรอกแล้วลองอีกครั้ง')}finally{setBusy(false)}};
 useEffect(()=>{apiClient.get<Recipe[]>('/business/analytics/cost-variance/recipes').then(x=>{setRecipes(x);const r=x.find(y=>y.versions.length);if(r){setRecipeId(r.id);setVersionId(r.versions.at(-1)!.id)}}).catch(()=>setError('โหลดรายการสูตรไม่สำเร็จ กรุณาลองใหม่'))},[]);
 useEffect(()=>{if(versionId){setOverrides([]);setPrices({});setYieldQty(undefined);setMargin(undefined);setMarkup(undefined);void apiClient.post<Result>('/business/analytics/profit-simulator/calculate',{recipeVersionId:versionId,ingredientOverrides:[],sellingPrices:{}}).then(setResult).catch(()=>setError('โหลดต้นทุนปัจจุบันไม่สำเร็จ'))}},[versionId]);
 const setRow=(itemId:string,patch:Partial<Override>)=>setOverrides(old=>[...old.filter(x=>x.itemId!==itemId),{...(old.find(x=>x.itemId===itemId)??{itemId}),...patch}]);const reset=()=>{setOverrides([]);setPrices({});setYieldQty(undefined);setMargin(undefined);setMarkup(undefined);void calculate({recipeVersionId:versionId,ingredientOverrides:[],sellingPrices:{}})};
 return <PageContainer size="wide" className="analytics-page simulator-page"><PageHeader breadcrumb="ต้นทุนและสูตร / จำลองต้นทุนและกำไร" title="จำลองต้นทุนและกำไร" description="WHAT-IF / PROFIT SIMULATOR — ทดลองปรับราคา วัตถุดิบ ปริมาณผลผลิต และราคาขาย โดยไม่กระทบข้อมูลจริง" actions={<><button className="btn" onClick={reset}><RotateCcw/>รีเซ็ตค่าจำลอง</button><button className="btn" disabled={!result} onClick={()=>void apiClient.downloadPost('/business/analytics/profit-simulator/export.xlsx',payload,{expect:'xlsx',fallbackName:'profit-simulation.xlsx'})}><Download/>ส่งออก Excel</button></>}/>
 <div className="simulation-banner"><StatusChip label="โหมดจำลอง / SIMULATION" tone="info"/><span>ข้อมูลในหน้านี้จะไม่ถูกบันทึกลงต้นทุนหรือราคาจริง</span></div><GuidanceCard><p>1. เลือกสูตรและเวอร์ชัน 2. ทดลองปรับจำนวนหรือต้นทุนวัตถุดิบ 3. ปรับผลผลิตและราคาขาย 4. กดคำนวณใหม่เพื่อดูผลลัพธ์</p></GuidanceCard>
 {error&&<div className="alert error" role="alert">{error}</div>}{result?.warnings.includes('COST_DATA_INCOMPLETE')&&<div className="alert warning"><TriangleAlert/>ต้นทุนยังไม่ครบ — คำนวณจากรายการที่มีข้อมูลแล้ว {result.coverage.known} จาก {result.coverage.eligible} รายการ</div>}{result?.warnings.includes('SIMULATED_PRICE_BELOW_SIMULATED_COST')&&<div className="alert error"><TriangleAlert/>ราคาขายจำลองต่ำกว่าต้นทุนจำลอง กรุณาตรวจสอบราคาขาย</div>}
 <div className="simulator-layout"><main className="simulator-main"><ContentCard title="1. เลือกสูตร / Recipe" description="เลือกสูตรและเวอร์ชันที่ต้องการใช้เป็นข้อมูลตั้งต้น"><div className="ops-field-grid"><label>สูตรอาหาร / Recipe<select value={recipeId} onChange={e=>{setRecipeId(e.target.value);setVersionId(recipes.find(x=>x.id===e.target.value)?.versions.at(-1)?.id??'')}}><option value="">เลือกสูตรอาหาร</option>{recipes.map(r=><option key={r.id} value={r.id}>{r.code} · {r.name}</option>)}</select><small>ระบบจะดึงต้นทุนและราคาขายปัจจุบันมาเป็นค่าตั้งต้น</small></label><label>เวอร์ชันสูตร / Version<select value={versionId} onChange={e=>setVersionId(e.target.value)}>{versions.map(v=><option key={v.id} value={v.id}>เวอร์ชัน {v.versionNo}</option>)}</select><small>การจำลองจะอ้างอิงวัตถุดิบของเวอร์ชันนี้</small></label></div></ContentCard>
 {!versionId?<EmptyState icon={FlaskConical} title="เลือกสูตรเพื่อเริ่มจำลองต้นทุนและกำไร" description="การจำลองไม่เปลี่ยนแปลงข้อมูลต้นทุนหรือราคาขายจริง"/>:<><ContentCard title="2. สมมติฐานวัตถุดิบ / Ingredient Assumptions" description="ปุ่มเปอร์เซ็นต์ทุกปุ่มคำนวณเทียบกับค่าปัจจุบัน ไม่ทบต้น"><div className="table-wrap"><table className="data-table simulator-table"><thead><tr><th>วัตถุดิบ</th><th className="num">จำนวนปัจจุบัน</th><th>จำนวนจำลอง</th><th className="num">ต้นทุนปัจจุบัน</th><th>ต้นทุนจำลอง</th><th className="num">ผลกระทบ</th><th><span className="sr-only">จัดการ</span></th></tr></thead><tbody>{result?.lines.map(line=>{const o=overrides.find(x=>x.itemId===line.itemId),status=displayEnum(line.costStatus),unit=displayUnit(line.unitCode);return <tr key={line.itemId}><td><b>{line.itemName}</b><small className="cell-sub"><StatusChip label={status.label} tone={status.tone}/>{line.manualCost&&' · ระบุเพื่อจำลองเท่านั้น'}</small></td><td className="num">{quantity(line.baselineQuantity)}<small className="cell-sub">{unit}</small></td><td><input aria-label={`จำนวนจำลอง ${line.itemName}`} type="number" min="0" step="0.0001" value={o?.quantity??line.simulatedQuantity} onChange={e=>setRow(line.itemId,{quantity:Number(e.target.value),quantityPercent:undefined})}/><Preset values={[-10,-5,5]} onPick={v=>setRow(line.itemId,{quantity:undefined,quantityPercent:v})}/><small className="cell-sub">{unit} · เทียบค่าปัจจุบัน</small></td><td className="num">{money(line.baselineUnitCost)}<small className="cell-sub">ต่อ {unit}</small></td><td><input aria-label={`ต้นทุนจำลอง ${line.itemName}`} type="number" min="0" step="0.0001" value={o?.unitCost??line.simulatedUnitCost??''} placeholder="เช่น 170.00" onChange={e=>setRow(line.itemId,{unitCost:e.target.value===''?undefined:Number(e.target.value),unitCostPercent:undefined})}/><Preset values={[-5,5,10]} onPick={v=>setRow(line.itemId,{unitCost:undefined,unitCostPercent:v})}/><small className="cell-sub">กรอกราคาต่อหน่วย เช่น 1 KG ราคา 170 บาท ให้กรอก 170</small></td><td className="num">{line.impact==null?'คำนวณไม่ได้':money(line.impact)}</td><td><button className="btn compact" onClick={()=>setOverrides(x=>x.filter(y=>y.itemId!==line.itemId))}>คืนค่า</button></td></tr>})}</tbody></table></div></ContentCard>
 <ContentCard title="3. ผลผลิต / Yield และราคาขาย / Selling Price"><div className="ops-field-grid"><label>จำนวนผลผลิตจำลอง / Yield Quantity <HelpTip label="Yield">ปริมาณสินค้าที่ได้จริงจากสูตร เช่น สูตรนี้ผลิตได้ 10 KG ให้กรอก 10</HelpTip><input type="number" min="0.0001" disabled={result?.version.yieldMode==='BATCH'} value={yieldQty??result?.simulated.effectiveYield??''} placeholder="เช่น 10" onChange={e=>setYieldQty(Number(e.target.value))}/><small>{result?.version.yieldMode==='BATCH'?'สูตรนี้คิดผลผลิตต่อหนึ่งชุด จึงแก้หน่วยผลผลิตไม่ได้':displayUnit(result?.version.yieldUnit)}</small></label>{result?.tiers.map(t=><label key={t.priceType}>{displayPriceType(t.priceType)}<input type="number" min="0" value={prices[t.priceType]??t.simulated?.sellingPrice??''} placeholder="เช่น 120.00" onChange={e=>setPrices(x=>({...x,[t.priceType]:Number(e.target.value)}))}/><Preset values={[5,10]} onPick={v=>{const base=t.baseline?.sellingPrice??0;setPrices(x=>({...x,[t.priceType]:base*(1+v/100)}))}}/><small>ราคาปัจจุบัน {money(t.baseline?.sellingPrice)} · ปุ่มเทียบค่าปัจจุบัน</small></label>)}</div></ContentCard>
 <ContentCard title="4. เป้าหมายกำไร / Profit Target"><div className="ops-field-grid"><label>อัตรากำไรเป้าหมาย / Target Margin % <HelpTip label="Margin">สัดส่วนกำไรเทียบกับราคาขาย</HelpTip><input type="number" max="99.9999" placeholder="เช่น 30" value={margin??''} onChange={e=>setMargin(e.target.value===''?undefined:Number(e.target.value))}/><small>ราคาขายที่ควรใช้ {money(result?.targets.margin?.rawSellingPrice)}</small></label><label>อัตราบวกจากต้นทุน / Target Markup % <HelpTip label="Markup">สัดส่วนกำไรเทียบกับต้นทุน</HelpTip><input type="number" min="-100" placeholder="เช่น 40" value={markup??''} onChange={e=>setMarkup(e.target.value===''?undefined:Number(e.target.value))}/><small>ราคาขายที่ควรใช้ {money(result?.targets.markup?.rawSellingPrice)}</small></label></div></ContentCard><button className="btn primary simulator-calculate" disabled={busy||!versionId} onClick={()=>void calculate()}>{busy?'กำลังคำนวณ…':'คำนวณใหม่ / Recalculate'}</button></>}
 </main><StickySummary><SimulationSummary result={result}/></StickySummary></div></PageContainer>}
function Preset({values,onPick}:{values:number[];onPick:(v:number)=>void}){return <div className="preset-row" aria-label="ค่าปรับด่วน เทียบค่าปัจจุบัน">{values.map(v=><button type="button" key={v} onClick={()=>onPick(v)}>{v>0?'+':''}{v}%</button>)}</div>}
function SimulationSummary({result}:{result?:Result}){return <div className="ops-sum simulation-summary"><span className="eyebrow">ผลลัพธ์จำลอง / SIMULATION RESULT</span><h2>ปัจจุบัน → จำลอง</h2>{!result?<p>เลือกสูตรเพื่อดูผลลัพธ์</p>:<><KPIGrid columns={2}><KPICard label="ต้นทุนปัจจุบัน / หน่วย" value={money(result.baseline.unitCost)}/><KPICard label="ต้นทุนจำลอง / หน่วย" value={money(result.simulated.unitCost)}/><KPICard label="ส่วนต่างต้นทุน" value={money(result.simulated.costChange)}/><KPICard label="ข้อมูลต้นทุนครบ" value={`${result.coverage.known}/${result.coverage.eligible} · ${result.coverage.percent.toFixed(0)}%`}/></KPIGrid><dl><div><dt>ผลจากวัตถุดิบและค่าใช้จ่าย</dt><dd>{money(result.bridge.ingredientImpactPerUnit)}</dd></div><div><dt>ผลจากจำนวนผลผลิต</dt><dd>{money(result.bridge.yieldImpactPerUnit)}</dd></div><div><dt>ผลร่วมและส่วนที่เหลือ</dt><dd>{money(result.bridge.interactionResidual)}</dd></div><div><dt>ราคาขายเท่าทุนขั้นต้น</dt><dd>{money(result.targets.breakEvenSellingPrice)}</dd></div></dl>{result.tiers.map(t=><div className="breakdown-row" key={t.priceType}><b>{displayPriceType(t.priceType)}</b><span>{money(t.simulated?.sellingPrice)}</span><small>กำไรขั้นต้น {money(t.simulated?.grossProfit)} · อัตรากำไร {t.simulated?.marginPercent?.toFixed(2)??'—'}% · อัตราบวกจากต้นทุน {t.simulated?.markupPercent?.toFixed(2)??'—'}%</small></div>)}<p className="ops-sum-note">เป็นกำไรขั้นต้นตามข้อมูลต้นทุนที่ระบบมี ไม่ใช่กำไรสุทธิทางบัญชี</p></>}</div>}
