import { useEffect, useState } from 'react';
import { Activity, ArrowRight, BellRing, Boxes, Calculator, CheckCircle2, ChefHat, ClipboardList, CookingPot, Landmark, PackageCheck, ReceiptText, ShieldCheck, TrendingUp, TriangleAlert, UsersRound } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useAuth } from '@/auth/AuthContext';
import { apiClient } from '@/lib/api-client';

type Order={id:string;orderNo:string;status:string;deliveryDate:string;deliveryTime?:string;totalAmount:string;customer:{name:string}};
type Kpi={totalOrders:number;todayOrders:number;monthOrders:number;revenueToday:string;revenueMonth:string;pendingRevenue:string};
type Summary={users:number;activeUsers:number;items:number;recipes:number;warehouses:number;itemsWithoutPrice:number};
type DashboardContent={eyebrow:string;title:string;intro:string;icon:typeof Boxes;actions:{label:string;path:string;icon:typeof Boxes}[]};
const content:Record<string,DashboardContent>={
 SUPER_ADMIN:{eyebrow:'SYSTEM COMMAND CENTER',title:'ศูนย์ควบคุมระบบ',intro:'กำกับบริษัท ผู้ใช้ สิทธิ์ ความปลอดภัย และภาพรวมธุรกิจจากจุดเดียว',icon:ShieldCheck,actions:[{label:'จัดการผู้ใช้งาน',path:'/users',icon:UsersRound},{label:'ตรวจสอบ Audit',path:'/activity',icon:Activity},{label:'ตั้งค่าบริษัท',path:'/settings',icon:Landmark}]},
 MANAGER:{eyebrow:'MANAGEMENT COMMAND CENTER',title:'ภาพรวมผู้บริหาร',intro:'ยอดขาย ออเดอร์ งานปฏิบัติการ ต้นทุน และความพร้อมที่ต้องตัดสินใจ',icon:TrendingUp,actions:[{label:'ออเดอร์ทั้งหมด',path:'/orders',icon:ReceiptText},{label:'วิเคราะห์ต้นทุน',path:'/costing',icon:Calculator},{label:'สรุปการขาย',path:'/sales',icon:TrendingUp}]},
 OPERATIONS:{eyebrow:'OPERATIONS COMMAND CENTER',title:'ศูนย์ปฏิบัติการ',intro:'รับของ • เบิกของ • เตรียมออเดอร์ • จัดการความพร้อมของครัวกลาง',icon:PackageCheck,actions:[{label:'รับของเข้า',path:'/receiving/new',icon:Boxes},{label:'เบิกของให้ครัวกลาง',path:'/stock-issues/new',icon:CookingPot},{label:'ดูออเดอร์',path:'/orders',icon:ClipboardList}]},
 ORDER_COORDINATOR:{eyebrow:'DELIVERY CONTROL',title:'ศูนย์ออเดอร์และการจัดส่ง',intro:'สร้างออเดอร์ล่วงหน้า ติดตามกำหนดส่ง สถานะ และยอดเงิน',icon:ReceiptText,actions:[{label:'สร้างออเดอร์',path:'/orders/new',icon:ReceiptText},{label:'ข้อมูลลูกค้า',path:'/customers',icon:UsersRound},{label:'ปฏิทินจัดส่ง',path:'/orders',icon:ClipboardList}]},
 CHEF:{eyebrow:'CHEF WORKSPACE',title:'วางแผนสูตรเมนูอาหาร',intro:'พัฒนาสูตร วางแผนวัตถุดิบ และส่งความต้องการให้ฝ่ายปฏิบัติการ',icon:ChefHat,actions:[{label:'คิดสูตรใหม่',path:'/recipes/new',icon:CookingPot},{label:'สูตรทั้งหมด',path:'/recipes',icon:ClipboardList},{label:'ความต้องการจากออเดอร์',path:'/orders',icon:Boxes}]},
 COSTING_STAFF:{eyebrow:'COST INTELLIGENCE',title:'ศูนย์วิเคราะห์ต้นทุน',intro:'เปลี่ยนข้อมูลวัตถุดิบ สูตร ราคา และ Margin ให้เป็นการตัดสินใจ',icon:Calculator,actions:[{label:'เพิ่มวัตถุดิบ',path:'/ingredients/new',icon:Boxes},{label:'สร้างสูตร',path:'/recipes/new',icon:CookingPot},{label:'ตั้งราคาขาย',path:'/pricing',icon:ReceiptText}]},
};
const money=(v:string|number|undefined)=>`฿${Number(v??0).toLocaleString('th-TH',{maximumFractionDigits:0})}`;
export default function RoleDashboardPage(){const {user}=useAuth();const role=user?.roles[0]??'COSTING_STAFF';const page=content[role]??content.COSTING_STAFF;const Icon=page.icon;const [kpi,setKpi]=useState<Kpi>();const [orders,setOrders]=useState<Order[]>([]);const [summary,setSummary]=useState<Summary>();
 useEffect(()=>{void Promise.allSettled([apiClient.get<Kpi>('/business/kpi'),apiClient.get<Order[]>('/business/orders'),apiClient.get<Summary>('/dashboard/summary')]).then(([a,b,c])=>{if(a.status==='fulfilled')setKpi(a.value);if(b.status==='fulfilled')setOrders(b.value);if(c.status==='fulfilled')setSummary(c.value);});},[user?.activeCompany?.id]);
 const waiting=orders.filter((o)=>['CONFIRMED','SENT_TO_PREP','PICKING'].includes(o.status));const near=orders.filter((o)=>new Date(o.deliveryDate).getTime()<=Date.now()+86400000&&!['DELIVERED','CANCELLED'].includes(o.status));const metric=role==='SUPER_ADMIN'?[['ผู้ใช้งาน',summary?.activeUsers??0,UsersRound],['สูตร',summary?.recipes??0,Activity],['คลังข้อมูล',summary?.items??0,Boxes],['รายการไม่มีราคา',summary?.itemsWithoutPrice??0,TriangleAlert]]:role==='COSTING_STAFF'?[['วัตถุดิบ/บรรจุภัณฑ์',summary?.items??0,Boxes],['สูตรที่ใช้งาน',summary?.recipes??0,CookingPot],['ออเดอร์เดือนนี้',kpi?.monthOrders??0,ReceiptText],['ยอดรอดำเนินการ',money(kpi?.pendingRevenue),Calculator]]:[['ออเดอร์วันนี้',kpi?.todayOrders??0,ReceiptText],['รอเตรียม',waiting.length,ClipboardList],['ใกล้ส่ง',near.length,TriangleAlert],['ยอดขายเดือนนี้',money(kpi?.revenueMonth),TrendingUp]];
 return <section className={`command-page role-${role.toLowerCase()}`}><header><div><span><BellRing/>{page.eyebrow}</span><h1>{page.title}</h1><p>{page.intro}</p><small>{user?.activeCompany?.nameTh} · {role.replaceAll('_',' ')}</small></div><Icon/></header><div className="command-kpis">{metric.map(([label,value,MetricIcon])=>{const M=MetricIcon as typeof Boxes;return <article key={String(label)}><M/><span>{label as string}</span><strong>{value as string|number}</strong></article>;})}</div><div className="command-layout"><main><section><div className="command-title"><div><small>LIVE WORKFLOW</small><h2>{role==='CHEF'?'สูตรและความต้องการที่กำลังทำ':'งานที่ต้องติดตาม'}</h2></div><Link to="/orders">ดูทั้งหมด <ArrowRight/></Link></div>{waiting.length?<div className="command-orders">{waiting.slice(0,6).map((order)=><article key={order.id}><span>{new Date(order.deliveryDate).toLocaleDateString('th-TH',{day:'numeric',month:'short'})}<small>{order.deliveryTime||'ไม่ระบุเวลา'}</small></span><div><strong>{order.orderNo}</strong><small>{order.customer.name}</small></div><b>{order.status.replaceAll('_',' ')}</b><em>{money(order.totalAmount)}</em></article>)}</div>:<div className="command-empty"><CheckCircle2/>ไม่มีงานค้างที่เข้าถึงได้ในขณะนี้</div>}</section></main><aside><small>QUICK ACTIONS</small><h2>เริ่มงานสำคัญ</h2>{page.actions.map(({label,path,icon:ActionIcon})=><Link key={path} to={path}><ActionIcon/><strong>{label}</strong><ArrowRight/></Link>)}</aside></div></section>}
