/* eslint-disable react-refresh/only-export-components -- provider module also exports locale utilities */
import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

export type Locale = 'th' | 'en' | 'zh-CN';
export const LOCALE_KEY = 's2a.locale';

export const messages = {
  th: {
    common: { language: 'เลือกภาษา', backHome: 'กลับหน้าหลัก', loading: 'กำลังเปิดหน้า…', save:'บันทึก', cancel:'ยกเลิก', edit:'แก้ไข', delete:'ลบ', add:'เพิ่ม', search:'ค้นหา', filter:'กรอง', back:'ย้อนกลับ', next:'ถัดไป', confirm:'ยืนยัน', close:'ปิด', download:'ดาวน์โหลด', print:'พิมพ์', sendEmail:'ส่งอีเมล', retry:'ลองใหม่', details:'ดูรายละเอียด', addItem:'เพิ่มรายการ', noData:'ยังไม่มีข้อมูล', noResults:'ไม่พบรายการ' },
    auth: { signIn: 'เข้าสู่ระบบ', subtitle: 'เข้าสู่พื้นที่ทำงานของคุณ', username: 'ชื่อผู้ใช้', password: 'รหัสผ่าน', usernamePlaceholder: 'กรอกชื่อผู้ใช้', passwordPlaceholder: 'กรอกรหัสผ่าน', remember: 'จำชื่อผู้ใช้', forgot: 'ลืมรหัสผ่าน?', signingIn: 'กำลังเข้าสู่ระบบ...', noAccount: 'ยังไม่มีบัญชี?', register: 'ลงทะเบียน', invalid: 'ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง', gatewayLead:'รู้', gatewayCost:'ต้นทุนจริง', gatewayBefore:'ก่อนกำหนด', gatewayPrice:'ราคาขาย', workspace:'พื้นที่ทำงาน' },
    register: { title: 'สร้างบัญชี S2A', subtitle: 'เริ่มต้นบัญชีสำหรับพื้นที่ทำงานใหม่หรือรอรับคำเชิญ', fullName: 'ชื่อ-นามสกุล', email: 'อีเมล', phone: 'โทรศัพท์ (ไม่บังคับ)', confirm: 'ยืนยันรหัสผ่าน', terms: 'ยอมรับเงื่อนไขการใช้งานและนโยบายความเป็นส่วนตัว', submit: 'สร้างบัญชี', submitting: 'กำลังสร้างบัญชี...', success: 'สร้างบัญชีสำเร็จ', pending: 'บัญชีของคุณยังไม่มีสิทธิ์ในบริษัทใด กรุณารอคำเชิญหรือการเปิดใช้งานพื้นที่ทำงาน', login: 'ไปหน้าเข้าสู่ระบบ' },
    company: { title: 'เลือกบริษัทที่ต้องการเข้าใช้งาน', subtitle: 'เลือกพื้นที่ทำงานตามสิทธิ์และหน้าที่ของคุณ', enter: 'เข้าใช้งาน', entering: 'กำลังเข้าใช้งาน…', add: 'เพิ่มบริษัท', signOut: 'ออกจากระบบ', primary: 'บริษัทหลัก', empty: 'ยังไม่มีบริษัทที่คุณมีสิทธิ์ใช้งาน' },
    cookie: { title: 'เราใส่ใจความเป็นส่วนตัวของคุณ', description: 'เราใช้คุกกี้ที่จำเป็นเพื่อให้เว็บไซต์ทำงานอย่างปลอดภัย และใช้การตั้งค่าที่คุณเลือกเพื่อปรับปรุงประสบการณ์', essential: 'คุกกี้ที่จำเป็น', essentialDescription: 'ใช้สำหรับความปลอดภัย การเข้าสู่ระบบ และการทำงานพื้นฐานของเว็บไซต์', always: 'เปิดเสมอ', preferences: 'การตั้งค่า', preferencesDescription: 'จดจำตัวเลือกการใช้งาน โดยไม่มีคุกกี้การตลาดในขณะนี้', accept: 'ยอมรับทั้งหมด', necessary: 'เฉพาะที่จำเป็น', settings: 'ตั้งค่าคุกกี้', save: 'บันทึกการตั้งค่า', policy: 'นโยบายคุกกี้' },
    home: { signIn: 'เข้าสู่ระบบ', dashboard: 'ไปที่แดชบอร์ด', hero: 'ระบบคิดคำนวณต้นทุนและคิดคำนวณสูตรเมนูอาหาร', support: 'จัดการวัตถุดิบ บรรจุภัณฑ์ สูตรอาหาร ต้นทุน ราคาขาย และกำไรในพื้นที่ทำงานเดียว', process: 'ดูการทำงานของระบบ', flow: ['วัตถุดิบ','สูตรอาหาร','ต้นทุน','ราคาขาย','กำไร'], flowDetails:['ราคาซื้อ หน่วย และต้นทุนฐาน','รวมวัตถุดิบและบรรจุภัณฑ์','คำนวณต้นทุนจริงต่อหน่วย','กำหนดราคาด้วย Markup หรือ Margin','เห็นกำไรของทุกเมนู'], nav:['เกี่ยวกับระบบ','ฟีเจอร์','วิธีการทำงาน','ภาพรวมระบบ'] },
    navigation: { overview:'ภาพรวม', ingredients:'วัตถุดิบ', packaging:'บรรจุภัณฑ์', recipes:'สูตรเมนูอาหาร', costing:'คำนวณต้นทุน', pricing:'ราคาขายและกำไร', catalog:'คลังข้อมูล', sales:'สรุปการขาย / KPI เมนู', orders:'ออเดอร์', customers:'ลูกค้า', receiving:'รับของเข้า', stockIssue:'เบิกให้ครัวกลาง', users:'ผู้ใช้งาน', activity:'ประวัติการใช้งาน', settings:'ตั้งค่าระบบ', menuCost:'จัดการเมนูและต้นทุน', dataSales:'ข้อมูลและยอดขาย', orderOperations:'ออเดอร์และปฏิบัติการ', system:'ระบบ', signOut:'ออกจากระบบ', closeMenu:'ปิดเมนู' },
    roles: { SUPER_ADMIN:'ผู้ดูแลระบบสูงสุด', MANAGER:'ผู้จัดการ', OPERATIONS:'ฝ่ายปฏิบัติการ', ORDER_COORDINATOR:'ผู้ประสานงานออเดอร์', CHEF:'เชฟ', COSTING_STAFF:'เจ้าหน้าที่ต้นทุน' },
    shell: { search:'ค้นหาเมนู เอกสาร หรือข้อมูล…', currentCompany:'บริษัทปัจจุบัน', changeCompany:'เปลี่ยนบริษัท', profile:'โปรไฟล์', changePassword:'เปลี่ยนรหัสผ่าน', notifications:'การแจ้งเตือน', all:'ทั้งหมด', unread:'ยังไม่อ่าน', action:'ต้องดำเนินการ', markAll:'ทำเครื่องหมายว่าอ่านทั้งหมด', noNotifications:'ไม่มีการแจ้งเตือนในหมวดนี้', newAppear:'รายการใหม่จะแสดงที่นี่', details:'ดูรายละเอียด' },
    validation: { mismatch:'รหัสผ่านทั้งสองช่องไม่ตรงกัน', duplicate:'ชื่อผู้ใช้หรืออีเมลนี้ถูกใช้งานแล้ว', rate:'มีการลงทะเบียนมากเกินไป กรุณาลองใหม่ภายหลัง', generic:'กรุณาตรวจสอบข้อมูลแล้วลองอีกครั้ง', passwordRules:'รหัสผ่านต้องมี', length:'อย่างน้อย 10 ตัวอักษร', upper:'ตัวพิมพ์ใหญ่ A–Z', lower:'ตัวพิมพ์เล็ก a–z', number:'ตัวเลข 0–9', special:'อักขระพิเศษ' },
    onboarding: { eyebrow:'WORKSPACE ONBOARDING', hero:'เริ่มต้นพื้นที่ทำงานของคุณกับ S2A', support:'สร้างบัญชีเพื่อเริ่มจัดการต้นทุน สูตรอาหาร ออเดอร์ และการปฏิบัติงานในระบบเดียว', security:'การลงทะเบียนนี้ยังไม่ให้สิทธิ์เข้าถึงบริษัทใดโดยอัตโนมัติ', steps:['สร้างบัญชี','สร้าง / เข้าร่วมบริษัท','กำหนดสิทธิ์','เริ่มใช้งาน'], account:'ข้อมูลบัญชี', protection:'ความปลอดภัย', agreement:'ข้อตกลง', already:'มีบัญชีอยู่แล้ว?' },
    status: { DRAFT:'ร่าง', CONFIRMED:'ยืนยันแล้ว', SENT_TO_PREP:'ส่งให้เตรียม', PICKING:'กำลังเบิก / เตรียม', ISSUED:'เบิกแล้ว', READY:'พร้อมส่ง', DELIVERED:'ส่งสำเร็จ', CANCELLED:'ยกเลิก' },
    errors: { VALIDATION_ERROR:'ข้อมูลไม่ถูกต้อง กรุณาตรวจสอบอีกครั้ง', UNAUTHORIZED:'กรุณาเข้าสู่ระบบ', FORBIDDEN:'คุณไม่มีสิทธิ์ดำเนินการนี้', NOT_FOUND:'ไม่พบข้อมูลที่ต้องการ', CONFLICT:'ข้อมูลขัดแย้งกับรายการที่มีอยู่', INSUFFICIENT_STOCK:'สต็อกไม่เพียงพอ', DUPLICATE:'มีข้อมูลนี้อยู่แล้ว', INTERNAL_ERROR:'ระบบขัดข้อง กรุณาลองใหม่', NETWORK_ERROR:'ไม่สามารถเชื่อมต่อระบบได้ กรุณาลองใหม่' },
    business: { orders:'ออเดอร์ลูกค้า', ordersDescription:'จัดการกำหนดส่ง รายการ ยอดเงิน และสถานะการเตรียม', createOrder:'สร้างออเดอร์', deliveryToday:'ส่งวันนี้', awaitingDelivery:'รอเตรียม / ส่ง', pendingRevenue:'ยอดรอส่ง', actualSales:'ยอดขายจริง', newOrder:'ออเดอร์ใหม่', customer:'ลูกค้า', selectCustomer:'เลือกลูกค้า', deliveryDate:'วันที่ส่ง', deliveryTime:'เวลาส่ง', menuCode:'รหัสเมนู', menuName:'ชื่อเมนู', quantity:'จำนวน', unit:'หน่วย', unitPrice:'ราคาต่อหน่วย', notes:'หมายเหตุ', saveDraft:'บันทึกร่าง', loadingOrders:'กำลังโหลดออเดอร์…', noOrders:'ยังไม่มีออเดอร์', noOrdersDescription:'สร้างออเดอร์รายการแรกเพื่อเริ่มวางแผนการเตรียม', orderNumber:'เลขที่', amount:'ยอดเงิน', status:'สถานะ', actions:'จัดการ', sendToPrep:'ส่งเตรียม', customers:'ลูกค้า', customersDescription:'ข้อมูลติดต่อ ออเดอร์ล่วงหน้า และยอดขายจริงจากออเดอร์ที่ส่งสำเร็จ', customerCode:'รหัสลูกค้า', customerName:'ชื่อลูกค้า / โรงเรียน', contact:'ผู้ติดต่อ', phone:'โทรศัพท์', email:'อีเมล', addCustomer:'เพิ่มลูกค้า', active:'ใช้งาน', totalOrders:'ออเดอร์ทั้งหมด', upcomingOrders:'ออเดอร์ล่วงหน้า', latest:'ล่าสุด', noCustomers:'ยังไม่มีข้อมูลลูกค้า', noTime:'ไม่ระบุเวลา', viewAll:'ดูทั้งหมด', quickActions:'เริ่มงานสำคัญ', liveWorkflow:'งานที่ต้องติดตาม', recipeWorkflow:'สูตรและความต้องการที่กำลังทำ', noPendingWork:'ไม่มีงานค้างที่เข้าถึงได้ในขณะนี้' },
  },
  en: {
    common: { language: 'Select language', backHome: 'Back to Home', loading: 'Loading…', save:'Save', cancel:'Cancel', edit:'Edit', delete:'Delete', add:'Add', search:'Search', filter:'Filter', back:'Back', next:'Next', confirm:'Confirm', close:'Close', download:'Download', print:'Print', sendEmail:'Send email', retry:'Try again', details:'View details', addItem:'Add item', noData:'No data yet', noResults:'No results found' },
    auth: { signIn: 'Sign in', subtitle: 'Access your secure workspace', username: 'Username', password: 'Password', usernamePlaceholder: 'Enter username', passwordPlaceholder: 'Enter password', remember: 'Remember username', forgot: 'Forgot password?', signingIn: 'Signing in...', noAccount: 'New to S2A?', register: 'Register', invalid: 'Incorrect username or password', gatewayLead:'Know the', gatewayCost:'True Cost', gatewayBefore:'before setting the', gatewayPrice:'Selling Price', workspace:'Workspace' },
    register: { title: 'Create your S2A account', subtitle: 'Start an account for a new workspace or wait for an invitation', fullName: 'Full Name', email: 'Email', phone: 'Phone (optional)', confirm: 'Confirm Password', terms: 'I accept the Terms of Use and Privacy Policy', submit: 'Create Account', submitting: 'Creating account...', success: 'Account created', pending: 'Your account has no company access yet. Please wait for an invitation or workspace activation.', login: 'Continue to Sign in' },
    company: { title: 'Select a company', subtitle: 'Choose a workspace available to your account', enter: 'Enter workspace', entering: 'Entering workspace…', add: 'Add company', signOut: 'Sign out', primary: 'Primary company', empty: 'No company workspace is currently assigned to your account' },
    cookie: { title: 'Your privacy matters', description: 'We use essential cookies to operate this site securely and preference cookies to remember your choices.', essential: 'Essential cookies', essentialDescription: 'Required for security, sign-in, and core website functions.', always: 'Always on', preferences: 'Preferences', preferencesDescription: 'Remembers your choices. We do not use marketing cookies at this time.', accept: 'Accept all', necessary: 'Essential only', settings: 'Cookie settings', save: 'Save preferences', policy: 'Cookie policy' },
    home: { signIn: 'Sign in', dashboard: 'Go to Dashboard', hero: 'Food Costing & Recipe Intelligence', support: 'Manage ingredients, packaging, recipes, costing, selling prices and profit in one workspace.', process: 'See how it works', flow: ['Ingredients','Recipe','Cost','Selling Price','Profit'], flowDetails:['Purchase price, units, and base cost','Combine ingredients and packaging','Calculate true unit cost','Set prices with markup or margin','Understand profit for every menu'], nav:['About','Features','How it works','Overview'] },
    navigation: { overview:'Overview', ingredients:'Ingredients', packaging:'Packaging', recipes:'Recipes', costing:'Costing', pricing:'Pricing & Profit', catalog:'Data Catalog', sales:'Sales / Menu KPI', orders:'Orders', customers:'Customers', receiving:'Receiving', stockIssue:'Issue to Central Kitchen', users:'Users', activity:'Activity Log', settings:'Settings', menuCost:'Menu & Cost Management', dataSales:'Data & Sales', orderOperations:'Orders & Operations', system:'System', signOut:'Sign out', closeMenu:'Close menu' },
    roles: { SUPER_ADMIN:'Super Administrator', MANAGER:'Manager', OPERATIONS:'Operations', ORDER_COORDINATOR:'Order Coordinator', CHEF:'Chef', COSTING_STAFF:'Costing Staff' },
    shell: { search:'Search menus, documents, or data…', currentCompany:'Current company', changeCompany:'Change company', profile:'Profile', changePassword:'Change password', notifications:'Notifications', all:'All', unread:'Unread', action:'Action required', markAll:'Mark all as read', noNotifications:'No notifications in this category', newAppear:'New items will appear here', details:'View details' },
    validation: { mismatch:'Passwords do not match', duplicate:'This username or email is already registered', rate:'Too many registration attempts. Please try again later.', generic:'Please check the form and try again.', passwordRules:'Password must include', length:'At least 10 characters', upper:'Uppercase A–Z', lower:'Lowercase a–z', number:'Number 0–9', special:'Special character' },
    onboarding: { eyebrow:'WORKSPACE ONBOARDING', hero:'Start your S2A workspace', support:'Create your account to manage costing, recipes, orders and operations in one system.', security:'Registration does not automatically grant access to any company.', steps:['Create Account','Create / Join Company','Set Permissions','Start Working'], account:'Account information', protection:'Security', agreement:'Agreement', already:'Already have an account?' },
    status: { DRAFT:'Draft', CONFIRMED:'Confirmed', SENT_TO_PREP:'Sent to Preparation', PICKING:'Picking / Preparing', ISSUED:'Issued', READY:'Ready', DELIVERED:'Delivered', CANCELLED:'Cancelled' },
    errors: { VALIDATION_ERROR:'Please check the information and try again.', UNAUTHORIZED:'Please sign in to continue.', FORBIDDEN:'You do not have permission to perform this action.', NOT_FOUND:'The requested information was not found.', CONFLICT:'This conflicts with an existing record.', INSUFFICIENT_STOCK:'Insufficient stock.', DUPLICATE:'This record already exists.', INTERNAL_ERROR:'Something went wrong. Please try again.', NETWORK_ERROR:'Unable to connect. Please try again.' },
    business: { orders:'Customer Orders', ordersDescription:'Manage delivery schedules, line items, totals, and preparation status.', createOrder:'Create Order', deliveryToday:'Delivering Today', awaitingDelivery:'Awaiting Preparation / Delivery', pendingRevenue:'Pending Revenue', actualSales:'Actual Sales', newOrder:'New Order', customer:'Customer', selectCustomer:'Select a customer', deliveryDate:'Delivery Date', deliveryTime:'Delivery Time', menuCode:'Menu Code', menuName:'Menu Name', quantity:'Quantity', unit:'Unit', unitPrice:'Unit Price', notes:'Notes', saveDraft:'Save Draft', loadingOrders:'Loading orders…', noOrders:'No Orders Yet', noOrdersDescription:'Create the first order to start planning preparation.', orderNumber:'Order No.', amount:'Amount', status:'Status', actions:'Actions', sendToPrep:'Send to Preparation', customers:'Customers', customersDescription:'Contact details, upcoming orders, and recognized sales from delivered orders.', customerCode:'Customer Code', customerName:'Customer / School Name', contact:'Contact', phone:'Phone', email:'Email', addCustomer:'Add Customer', active:'Active', totalOrders:'Total Orders', upcomingOrders:'Upcoming Orders', latest:'Latest', noCustomers:'No customers yet', noTime:'Time not specified', viewAll:'View All', quickActions:'Start Important Work', liveWorkflow:'Work Requiring Attention', recipeWorkflow:'Recipes and Current Requirements', noPendingWork:'There is no accessible pending work right now.' },
  },
  'zh-CN': {
    common: { language: '选择语言', backHome: '返回首页', loading: '正在加载…', save:'保存', cancel:'取消', edit:'编辑', delete:'删除', add:'添加', search:'搜索', filter:'筛选', back:'返回', next:'下一步', confirm:'确认', close:'关闭', download:'下载', print:'打印', sendEmail:'发送邮件', retry:'重试', details:'查看详情', addItem:'添加项目', noData:'暂无数据', noResults:'未找到结果' },
    auth: { signIn: '登录', subtitle: '进入您的安全工作区', username: '用户名', password: '密码', usernamePlaceholder: '请输入用户名', passwordPlaceholder: '请输入密码', remember: '记住用户名', forgot: '忘记密码？', signingIn: '正在登录...', noAccount: '还没有账户？', register: '注册', invalid: '用户名或密码不正确', gatewayLead:'掌握', gatewayCost:'真实成本', gatewayBefore:'再制定', gatewayPrice:'销售价格', workspace:'工作区' },
    register: { title: '创建 S2A 账户', subtitle: '创建新工作区账户，或等待企业邀请', fullName: '姓名', email: '电子邮箱', phone: '电话（选填）', confirm: '确认密码', terms: '我同意使用条款和隐私政策', submit: '创建账户', submitting: '正在创建账户...', success: '账户创建成功', pending: '您的账户尚未获得任何公司权限。请等待邀请或工作区开通。', login: '前往登录' },
    company: { title: '选择公司', subtitle: '请选择您有权访问的工作区', enter: '进入工作区', entering: '正在进入工作区…', add: '添加公司', signOut: '退出登录', primary: '主要公司', empty: '您的账户目前尚未分配公司工作区' },
    cookie: { title: '我们重视您的隐私', description: '我们使用必要 Cookie 保障网站安全运行，并使用偏好 Cookie 记住您的选择。', essential: '必要 Cookie', essentialDescription: '用于安全、登录和网站基本功能。', always: '始终启用', preferences: '偏好设置', preferencesDescription: '用于记住您的选择。目前不使用营销 Cookie。', accept: '全部接受', necessary: '仅必要项', settings: 'Cookie 设置', save: '保存设置', policy: 'Cookie 政策' },
    home: { signIn: '登录', dashboard: '前往仪表板', hero: '食品成本与配方管理系统', support: '在一个工作空间中管理原料、包装、配方、成本、售价与利润。', process: '查看工作流程', flow: ['原料','配方','成本','售价','利润'], flowDetails:['采购价、单位与基础成本','组合原料与包装','计算真实单位成本','按加价率或利润率定价','掌握每道菜单的利润'], nav:['系统介绍','功能','工作流程','系统概览'] },
    navigation: { overview:'概览', ingredients:'原料', packaging:'包装', recipes:'配方', costing:'成本计算', pricing:'售价与利润', catalog:'数据目录', sales:'销售 / 菜单 KPI', orders:'订单', customers:'客户', receiving:'入库', stockIssue:'发料至中央厨房', users:'用户', activity:'操作记录', settings:'系统设置', menuCost:'菜单与成本管理', dataSales:'数据与销售', orderOperations:'订单与运营', system:'系统', signOut:'退出登录', closeMenu:'关闭菜单' },
    roles: { SUPER_ADMIN:'超级管理员', MANAGER:'管理员', OPERATIONS:'运营', ORDER_COORDINATOR:'订单协调员', CHEF:'厨师', COSTING_STAFF:'成本专员' },
    shell: { search:'搜索菜单、文档或数据…', currentCompany:'当前公司', changeCompany:'切换公司', profile:'个人资料', changePassword:'修改密码', notifications:'通知', all:'全部', unread:'未读', action:'待处理', markAll:'全部标为已读', noNotifications:'此分类暂无通知', newAppear:'新项目将显示在这里', details:'查看详情' },
    validation: { mismatch:'两次输入的密码不一致', duplicate:'该用户名或邮箱已注册', rate:'注册尝试次数过多，请稍后再试。', generic:'请检查表单后重试。', passwordRules:'密码必须包含', length:'至少 10 个字符', upper:'大写字母 A–Z', lower:'小写字母 a–z', number:'数字 0–9', special:'特殊字符' },
    onboarding: { eyebrow:'WORKSPACE ONBOARDING', hero:'开始您的 S2A 工作空间', support:'创建账户，在一个系统中管理成本、配方、订单和运营流程。', security:'注册不会自动授予任何公司的访问权限。', steps:['创建账户','创建 / 加入公司','设置权限','开始使用'], account:'账户信息', protection:'安全设置', agreement:'协议', already:'已有账户？' },
    status: { DRAFT:'草稿', CONFIRMED:'已确认', SENT_TO_PREP:'已发送准备', PICKING:'正在备料', ISSUED:'已发料', READY:'已就绪', DELIVERED:'已送达', CANCELLED:'已取消' },
    errors: { VALIDATION_ERROR:'请检查输入信息后重试。', UNAUTHORIZED:'请登录后继续。', FORBIDDEN:'您没有执行此操作的权限。', NOT_FOUND:'未找到所需信息。', CONFLICT:'该信息与现有记录冲突。', INSUFFICIENT_STOCK:'库存不足。', DUPLICATE:'该记录已存在。', INTERNAL_ERROR:'系统出现问题，请重试。', NETWORK_ERROR:'无法连接系统，请重试。' },
    business: { orders:'客户订单', ordersDescription:'管理交付日期、订单项目、金额及备货状态。', createOrder:'创建订单', deliveryToday:'今日交付', awaitingDelivery:'等待备货 / 交付', pendingRevenue:'待交付金额', actualSales:'实际销售额', newOrder:'新订单', customer:'客户', selectCustomer:'选择客户', deliveryDate:'交付日期', deliveryTime:'交付时间', menuCode:'菜品编码', menuName:'菜品名称', quantity:'数量', unit:'单位', unitPrice:'单价', notes:'备注', saveDraft:'保存草稿', loadingOrders:'正在加载订单…', noOrders:'暂无订单', noOrdersDescription:'创建首个订单以开始安排备货。', orderNumber:'订单号', amount:'金额', status:'状态', actions:'操作', sendToPrep:'发送备货', customers:'客户', customersDescription:'管理联系信息、未来订单及已交付订单的实际销售额。', customerCode:'客户编码', customerName:'客户 / 学校名称', contact:'联系人', phone:'电话', email:'电子邮箱', addCustomer:'添加客户', active:'启用', totalOrders:'订单总数', upcomingOrders:'未来订单', latest:'最近', noCustomers:'暂无客户', noTime:'未指定时间', viewAll:'查看全部', quickActions:'开始重要工作', liveWorkflow:'待跟进工作', recipeWorkflow:'当前配方与需求', noPendingWork:'当前没有可访问的待处理工作。' },
  },
} as const;

const detect = (): Locale => { const saved = localStorage.getItem(LOCALE_KEY); if (saved === 'th' || saved === 'en' || saved === 'zh-CN') return saved; const language = navigator.language.toLowerCase(); return language.startsWith('zh') ? 'zh-CN' : language.startsWith('en') ? 'en' : 'th'; };
type I18nValue = (typeof messages)[Locale];
const I18nContext = createContext({ locale: 'th' as Locale, setLocale: (_: Locale) => {}, messages: messages.th as I18nValue });
export function I18nProvider({ children }: { children: ReactNode }) { const [locale, setLocaleState] = useState<Locale>(detect); const setLocale = (next: Locale) => { localStorage.setItem(LOCALE_KEY, next); setLocaleState(next); }; useEffect(() => { document.documentElement.lang = locale; document.title = locale === 'th' ? 'S2A ERP — ระบบต้นทุนอาหาร' : locale === 'en' ? 'S2A ERP — Food Cost Intelligence' : 'S2A ERP — 食品成本管理'; }, [locale]); const value = useMemo(() => ({ locale, setLocale, messages: messages[locale] as I18nValue }), [locale]); return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>; }
export const useI18n = () => useContext(I18nContext);
export const localeTag = (locale: Locale) => locale === 'th' ? 'TH' : locale === 'en' ? 'EN' : '中文';
export const formatCurrency = (value: number, locale: Locale = 'th') => new Intl.NumberFormat(locale === 'th' ? 'th-TH' : locale, { style: 'currency', currency: 'THB', currencyDisplay: locale === 'th' ? 'narrowSymbol' : 'code' }).format(value);
export const formatNumber = (value: number, locale: Locale = 'th', maximumFractionDigits = 2) => new Intl.NumberFormat(locale === 'th' ? 'th-TH' : locale, { maximumFractionDigits }).format(value);
export const formatDate = (value: Date | string, locale: Locale = 'th', options: Intl.DateTimeFormatOptions = { dateStyle: 'medium' }) => new Intl.DateTimeFormat(locale === 'th' ? 'th-TH' : locale, options).format(new Date(value));
export const navigationKeyByPath = { '/dashboard':'overview','/ingredients':'ingredients','/packaging':'packaging','/recipes':'recipes','/costing':'costing','/pricing':'pricing','/catalog':'catalog','/sales':'sales','/orders':'orders','/customers':'customers','/receiving':'receiving','/stock-issues':'stockIssue','/users':'users','/activity':'activity','/settings':'settings' } as const;
